import type {FaqEntry} from './guideFaq';
// Reviewed against manufacturer guidance; video audit and sources in docs/WOOD-OVEN-CONTENT-AUDIT.md.
export const WOOD_OVEN_FAQ: Record<'preheat'|'bake',FaqEntry[]> = {
 preheat: [
  {q:{fr:'Au bois : comment démarrer et placer le feu ?',en:'With wood: how should I start and position the fire?'},a:{fr:'Commencez par du petit bois sec et un allume-feu adapté à la cuisson, puis ajoutez progressivement des bûchettes en laissant circuler l’air. Dans un four traditionnel en briques ou pierre prévu pour cela, chauffez d’abord la zone de cuisson, puis déplacez le feu sur le côté. Dans un four à panier, gardez le combustible dans son foyer prévu ; ne bloquez pas l’entrée.',en:'Start with dry kindling and a cooking-safe firelighter, then add small split logs gradually, leaving air gaps. In a traditional brick or stone oven designed for it, heat the cooking area first, then move the fire to the side. In a basket-fed oven, keep fuel in its designated firebox; keep the entrance clear.'}},
  {q:{fr:'Quel bois choisir et pourquoi mon feu fume-t-il ?',en:'Which wood should I use, and why is my fire smoky?'},a:{fr:'Choisissez du bois dur bien sec, non traité, aux dimensions prévues par le fabricant. Pommier et cerisier ne sont pas à exclure systématiquement. Une fumée persistante invite à vérifier l’humidité du bois et l’arrivée d’air. Rechargez peu à peu sur un feu établi ; ne stockez pas de bûches dans le four pour les sécher.',en:'Choose dry, untreated hardwood sized for the oven. Apple and cherry are not universally unsuitable. Persistent smoke calls for checking wood moisture and airflow. Add small amounts to an established fire; do not store logs inside the oven to dry them.'}},
  {q:{fr:'Comment enlever les cendres avant d’enfourner ?',en:'How should I clear ash before launching?'},a:{fr:'Dégagez la zone de cuisson avec les outils adaptés au four, puis une brosse prévue pour sa sole ; vérifiez qu’elle ne laisse aucun débris. Gardez la pelle à pizza propre, séparée du tisonnier et de la pelle à braises. Les cendres ne parfument pas la pizza. Pas d’eau ni de chiffon humide sur la pierre, sauf méthode expressément autorisée par sa notice.',en:'Clear the cooking area with suitable oven tools, then a brush approved for its floor; check for loose debris. Keep the pizza peel clean and separate from the poker and ember shovel. Ash does not season pizza. Do not wet the stone or use a damp cloth unless its manual expressly permits that method.'}},
  {q:{fr:'Faut-il un porte-bûches et peut-on fermer la porte ?',en:'Do I need a log stand, and can I close the door?'},a:{fr:'Utilisez seulement les supports prévus pour votre four : l’essentiel est de laisser l’air alimenter le feu. Ne fermez jamais une porte étanche sur un feu actif. Certains fours compacts fonctionnent porte fermée avec leurs évents ouverts : suivez la notice du modèle et du combustible, sans obstruer l’évacuation.',en:'Use only supports approved for your oven: the fire needs airflow. Never seal an active fire behind an airtight door. Some compact ovens operate with their door closed and vents open; follow the instructions for the model and fuel, keeping the exhaust clear.'}},
 ],
 bake: [
  {q:{fr:'Le dessous brûle avant que le dessus soit cuit',en:'The base burns before the top is done'},a:{fr:'Vérifiez la température de la zone de sole choisie et éloignez la pizza du feu. Pour la suivante, attendez que cette zone refroidisse ou choisissez une zone moins chaude. Si la base est déjà cuite, finissez brièvement le dessus à la chaleur de la voûte en surveillant constamment.',en:'Check the temperature of your chosen floor area and move the pizza away from the fire. For the next pizza, let that area cool or choose a cooler spot. If the base is already done, briefly finish the top with dome heat while watching continuously.'}},

  {q:{fr:'La pizza colle à la pelle : que faire ?',en:'The pizza sticks to the peel: what should I do?'},a:{fr:'Avant d’approcher du four, vérifiez la glisse avec un petit mouvement de pelle. Soulevez doucement la zone collée et ajoutez juste un peu de farine dessous. Évitez l’excès de farine et les garnitures détrempées ; ne mettez pas de papier cuisson dans un four à pizza à très haute température.',en:'Check that the pizza slides with a small shake before approaching the oven. Gently lift the stuck area and add a little flour underneath. Avoid excess flour and wet toppings; do not use baking parchment in a very hot pizza oven.'}},

  {q:{fr:'Quand commencer à tourner la pizza ?',en:'When should I start turning the pizza?'},a:{fr:'Attendez que la base se tienne et que la pelle puisse passer dessous sans déchirer la pâte. Tournez ensuite selon la coloration, sans imposer un intervalle fixe. Si une zone de sole a refroidi, déplacez la pizza vers une zone plus chaude après avoir vérifié son dessous.',en:'Wait until the base holds together and the peel slides underneath without tearing it. Then turn according to colour rather than a fixed interval. If one floor area has cooled, move to a hotter spot after checking the underside.'}},
  {q:{fr:'Au bois : comment relancer la chaleur entre les pizzas ?',en:'With wood: how do I recover heat between pizzas?'},a:{fr:'Ajoutez une petite bûchette sèche au feu établi, puis attendez une combustion nette et la remontée de la sole. Ne jetez jamais de farine pour créer une flamme. Dans un four traditionnel en briques ou pierre compatible, des braises peuvent réchauffer une zone vide : retirez-les, brossez puis mesurez avant de reprendre, sans délai universel de 10–15 minutes.',en:'Add a small dry split to the established fire, then wait for clean combustion and floor recovery. Never throw flour to create flames. In a compatible traditional brick or stone oven, embers can reheat an empty area: remove them, brush and measure before resuming, rather than relying on a universal 10–15 minute interval.'}},
  {q:{fr:'Soulever la pizza lui donne-t-il un goût de bois ?',en:'Does lifting the pizza give it wood flavour?'},a:{fr:'Ce geste sert surtout à finir le dessus par la chaleur de la voûte lorsque la base est déjà cuite. Surveillez sans quitter la pizza des yeux et évitez le contact avec les flammes ou la voûte. Ne recherchez pas une couche de fumée ni un temps fixe de 2–3 secondes.',en:'Lifting mainly uses dome heat to finish the top when the base is already done. Watch continuously and avoid contact with flames or the dome. Do not aim for a smoke layer or rely on a fixed 2–3 seconds.'}},
  {q:{fr:'Après la cuisson, faut-il garder les cendres ?',en:'After cooking, should I leave the ash?'},a:{fr:'Ne conservez pas une couche de cendres sur la zone de cuisson pour régler sa température. Suivez la notice pour l’arrêt et le nettoyage du foyer ; attendez le refroidissement complet avant de retirer les cendres. La sole propre et sa température mesurée sont vos repères pour la prochaine cuisson.',en:'Do not retain an ash layer on the cooking area to regulate its temperature. Follow the shutdown and firebox-cleaning instructions; let the oven cool completely before removing ash. A clean floor and its measured temperature guide the next bake.'}},
 ],
};
