// ══════════════════════════════════════════
// BAKER HUB — Master Data File
// Single source of truth for all recipe data
// ══════════════════════════════════════════

// ── PIZZA STYLES ──────────────────────────
export const PIZZA_STYLES = {
  neapolitan: {
    name: 'Classic Neapolitan',
    emoji: '🔥',
    image: '/Neapolitan.png',
    desc: 'Light, airy, charred cornicione.',
    hydration: 62, salt: 2.8, yeast: 0.08,
    oil: 0, sugar: 0,
    pref: 'none', bulkH: 3, ballW: 270,
    ovenNote: 'No oil or sugar — these burn at 450°C+.',
    flourNote: 'Caputo 00 Pizzeria or equivalent.',
  },
  newyork: {
    name: 'New York Style',
    emoji: '🗽',
    image: '/Newyork.png',
    desc: 'Foldable, crispy-edged big slices.',
    hydration: 62, salt: 2.5, yeast: 0.3,
    oil: 2, sugar: 0.8,
    pref: 'poolish', bulkH: 3.5, ballW: 300,
    ovenNote: 'Oil and sugar help browning at lower home oven temps.',
    flourNote: 'High-gluten bread flour (13%+ protein).',
  },
  roman: {
    name: 'Roman Teglia',
    emoji: '🏛️',
    image: '/Roman.png',
    desc: 'High-hydration, ultra-crispy rectangular.',
    hydration: 78, salt: 2.5, yeast: 0.2,
    oil: 3, sugar: 0,
    pref: 'biga', bulkH: 4, ballW: 700,
    ovenNote: 'Oil is essential for the crispy base.',
    flourNote: 'Strong flour W300+ for high hydration.',
  },
  pan: {
    name: 'Pan / Detroit',
    emoji: '🍞',
    image: '/Detroit.png',
    desc: 'Thick, fluffy, crispy-bottomed.',
    hydration: 70, salt: 2.5, yeast: 0.5,
    oil: 4, sugar: 0.5,
    pref: 'none', bulkH: 3, ballW: 600,
    ovenNote: 'High oil content — effectively fried in the pan.',
    flourNote: 'Bread flour for strong gluten structure.',
  },
  sourdough: {
    name: 'Sourdough Pizza',
    emoji: '🌾',
    image: '/Sourdough.png',
    desc: 'Complex, tangy, naturally leavened.',
    hydration: 72, salt: 2.5, yeast: 0,
    oil: 0, sugar: 0,
    pref: 'levain', bulkH: 5, ballW: 280,
    ovenNote: 'No commercial yeast — starter only.',
    flourNote: 'Strong 00 or bread flour for long ferment.',
  },
} as const;

// ── BREAD STYLES ──────────────────────────
export const BREAD_STYLES = {
  pain_campagne: {
    name: 'Pain de campagne',
    emoji: '🍞',
    image: '/pain_campagne.png',
    desc: 'Rustic country bread. Wheat and rye blend, thick crust.',
    hydration: 72,
    salt: 2.0,
    yeast: 0.15,
    oil: 0,
    sugar: 0,
    pref: 'none',
    bulkH: 4,
    ballW: 800,
    ovenNote: 'Dutch oven: 240°C lid on 20min, lid off 20min.',
    flourNote: 'T65 or blend T65 + 10% T130 rye.',
  },
  pain_levain: {
    name: 'Pain au levain',
    emoji: '🫙',
    image: '/pain_levain.png',
    desc: 'Wild yeast sourdough. Deep flavour, open crumb.',
    hydration: 75,
    salt: 2.0,
    yeast: 0,
    oil: 0,
    sugar: 0,
    pref: 'levain',
    bulkH: 5,
    ballW: 900,
    ovenNote: 'Dutch oven: 250°C lid on 20min, lid off 25min.',
    flourNote: 'Strong T65 or bread flour.',
  },
  baguette: {
    name: 'Baguette',
    emoji: '🥖',
    image: '/baguette.png',
    desc: 'Crispy crust, airy crumb. The French classic.',
    hydration: 68,
    salt: 2.2,
    yeast: 0.3,
    oil: 0,
    sugar: 0,
    pref: 'poolish',
    bulkH: 3,
    ballW: 350,
    ovenNote: 'Steam essential — add ice cubes to oven tray.',
    flourNote: 'T55 or plain bread flour.',
  },
  pain_complet: {
    name: 'Pain complet',
    emoji: '🌾',
    image: '/pain_complet.png',
    desc: 'Wholemeal loaf. Nutty, dense, nutritious.',
    hydration: 70,
    salt: 2.0,
    yeast: 0.4,
    oil: 1,
    sugar: 0,
    pref: 'none',
    bulkH: 3,
    ballW: 750,
    ovenNote: 'Score deeply — wholemeal dough is denser.',
    flourNote: 'T110 or T150 wholemeal flour.',
  },
  pain_seigle: {
    name: 'Pain de seigle',
    emoji: '🌑',
    image: '/pain_seigle.png',
    desc: 'Dark rye bread. Dense, earthy, long-lasting.',
    hydration: 78,
    salt: 2.2,
    yeast: 0.5,
    oil: 0,
    sugar: 0,
    pref: 'none',
    bulkH: 2,
    ballW: 700,
    ovenNote: 'Bake in a loaf tin. Rye spreads without support.',
    flourNote: 'T130 or T170 rye flour, minimum 60% rye.',
  },
  fougasse: {
    name: 'Fougasse',
    emoji: '🌿',
    image: '/fougasse.png',
    desc: 'Provençal flatbread. Olive oil, scored leaf pattern.',
    hydration: 70,
    salt: 2.2,
    yeast: 0.5,
    oil: 4,
    sugar: 0,
    pref: 'none',
    bulkH: 2,
    ballW: 400,
    ovenNote: 'Flatten, cut leaf pattern, bake 220°C 15–18min.',
    flourNote: 'T55 or T65.',
  },
  brioche: {
    name: 'Brioche',
    emoji: '🥐',
    image: '/brioche.png',
    desc: 'Enriched, buttery, pillowy soft.',
    hydration: 55,
    salt: 2.0,
    yeast: 0.8,
    oil: 0,
    sugar: 4,
    pref: 'none',
    bulkH: 3,
    ballW: 500,
    ovenNote: 'Egg wash for golden colour. 180°C fan.',
    flourNote: 'T45 — lower protein for tenderness.',
  },
  pain_mie: {
    name: 'Pain de mie',
    emoji: '🍞',
    image: '/pain_mie.png',
    desc: 'Soft sandwich loaf. Fine crumb, thin crust.',
    hydration: 62,
    salt: 1.8,
    yeast: 0.6,
    oil: 3,
    sugar: 2,
    pref: 'none',
    bulkH: 2,
    ballW: 600,
    ovenNote: 'Bake in a Pullman tin with lid for square slices.',
    flourNote: 'T55 or plain flour.',
  },
  pain_viennois: {
    name: 'Pain viennois',
    emoji: '🥐',
    image: '/pain_viennois.png',
    desc: 'Viennese soft roll. Slightly sweet, milk-enriched.',
    hydration: 58,
    salt: 1.8,
    yeast: 0.7,
    oil: 2,
    sugar: 5,
    pref: 'none',
    bulkH: 2,
    ballW: 120,
    ovenNote: 'Egg wash. Score with scissors for classic look.',
    flourNote: 'T45 or T55.',
  },
} as const;

// ── OVEN TYPES ────────────────────────────
export const OVEN_TYPES = {
  pizza_oven: {
    name: 'Pizza oven',
    emoji: '🔥',
    desc: 'Ooni, Gozney, wood-fired. 450°C+',
    hydrationDelta: -3,
    forceOil: 0,
    forceSugar: 0,
    preheatMin: 45,
    tempNote: 'Preheat 45 min. Cook 60–90 seconds.',
  },
  home_oven_steel: {
    name: 'Home oven + steel/stone',
    emoji: '🪨',
    desc: 'Standard oven with baking steel or stone.',
    hydrationDelta: 3,
    forceOil: null,
    forceSugar: null,
    preheatMin: 60,
    tempNote: 'Preheat steel/stone 1h at max temp. Cook 5–7 min.',
  },
  home_oven_standard: {
    name: 'Home oven (standard)',
    emoji: '🏠',
    desc: 'Standard oven, no steel or stone.',
    hydrationDelta: 5,
    forceOil: null,
    forceSugar: null,
    preheatMin: 30,
    tempNote: 'Preheat 30 min at 230°C. Cook 8–12 min.',
  },
  electric_pizza: {
    name: 'Electric pizza oven',
    emoji: '⚡',
    desc: 'Breville, Effeuno, G3 Ferrari. 400°C.',
    hydrationDelta: -1,
    forceOil: 0,
    forceSugar: 0,
    preheatMin: 30,
    tempNote: 'Preheat 30 min at max. Cook 2–4 min.',
  },
} as const;

// ── MIXER TYPES ───────────────────────────
export const MIXER_TYPES = {
  hand: {
    name: 'By Hand',
    emoji: '🙌',
    desc: 'Classic technique',
    maxHydration: 70,
    kneadMin: 10,
    folds: 4,
    instructions: 'Mix until shaggy, rest 20 min (autolyse), then knead 8–10 min until smooth and elastic. Dough passes windowpane test.',
  },
  stand: {
    name: 'Stand Mixer',
    emoji: '⚙️',
    desc: 'KitchenAid, Kenwood, Bosch',
    maxHydration: 72,
    kneadMin: 8,
    folds: 2,
    instructions: 'Speed 1 for 2 min to combine, Speed 2 for 6–8 min until dough clears the bowl.',
  },
  spiral: {
    name: 'Spiral Mixer',
    emoji: '🌀',
    desc: 'Ooni Halo, Famag, Sunmix',
    maxHydration: 100,
    kneadMin: 14,
    folds: 1,
    instructions: '1st speed 3 min, 2nd speed 5–7 min. Handles high hydration effortlessly. In hot kitchens (≥26°C): add ice cubes directly into the mixing bowl with the water — the breaker bar will break them down as mixing progresses. This is the professional technique used in pizzerias in warm climates. Aim for roughly 20–30% ice by weight of your total water. For other mixers use ice-cold water only — ice cubes can damage stand mixer hooks.',
  },
  no_knead: {
    name: 'No-Knead',
    emoji: '⏰',
    desc: 'Time does the work',
    maxHydration: 100,
    kneadMin: 0,
    folds: 4,
    instructions: 'Mix just until no dry flour remains (~2 min). Time and stretch & folds develop the gluten.',
  },
} as const;

// ── YEAST TYPES ───────────────────────────
export const YEAST_TYPES = {
  instant: {
    name: 'Instant Dry',
    shortName: 'IDY',
    emoji: '🟡',
    also: 'Rapid rise, Fast action, Easy bake',
    form: 'Fine powder or tiny granules',
    color: 'Light beige/cream',
    usage: 'Add directly to flour — no proofing needed',
    shelfLife: '1–2 years sealed',
    conversion: 1.00,
    commonIn: 'Europe, professional baking',
  },
  active_dry: {
    name: 'Active Dry',
    shortName: 'ADY',
    emoji: '🟤',
    also: 'Traditional yeast, Dry yeast',
    form: 'Larger brown granules',
    color: 'Tan/brown',
    usage: 'Dissolve in warm water (38–43°C) for 5–10 min before adding to flour',
    shelfLife: '1 year sealed',
    conversion: 1.33,
    commonIn: 'USA, widely available',
  },
  fresh: {
    name: 'Fresh Yeast',
    shortName: 'Fresh',
    emoji: '🧱',
    also: 'Cake yeast, Compressed yeast',
    form: 'Soft block, crumbly',
    color: 'Beige/grey, slightly moist',
    usage: 'Crumble directly into dough or dissolve in water',
    shelfLife: '1–2 weeks refrigerated',
    conversion: 3.00,
    commonIn: 'Professional bakeries, Europe',
  },
  sourdough: {
    name: 'Sourdough Starter',
    shortName: 'Starter',
    emoji: '🫙',
    also: 'Levain, Wild yeast',
    form: 'Thick paste or liquid',
    color: 'Off-white to grey',
    usage: 'Feed 4–12h before use. Use at peak activity.',
    shelfLife: 'Indefinite if maintained',
    conversion: 0,
    commonIn: 'Artisan baking worldwide',
  },
} as const;

// ── TYPE EXPORTS ──────────────────────────
export type PizzaStyleKey = keyof typeof PIZZA_STYLES;
export type BreadStyleKey = keyof typeof BREAD_STYLES;
export type StyleKey = PizzaStyleKey | BreadStyleKey;
export type BakeType = 'pizza' | 'bread';
export type OvenType = keyof typeof OVEN_TYPES;
export type MixerType = keyof typeof MIXER_TYPES;
export type YeastType = keyof typeof YEAST_TYPES;

export const ALL_STYLES = { ...PIZZA_STYLES, ...BREAD_STYLES };