export type FlourEntry = {
  id: string;
  brand: string;
  name: string;
  type: '00' | '0' | '1' | '2' | 'T45' | 'T55' | 'T65' | 'T80'
      | 'T110' | 'T150' | 'bread' | 'all_purpose' | 'high_gluten'
      | 'wholemeal' | 'rye' | 'spelt' | 'semolina';
  country: 'it' | 'fr' | 'uk' | 'us' | 'ca' | 'sg' | 'au' | 'de'
         | 'jp' | 'kr' | 'cn' | 'in' | 'th' | 'id' | 'my' | 'ph'
         | 'vn' | 'br' | 'mx' | 'ar' | 'se' | 'fi' | 'no' | 'nl'
         | 'pl' | 'at';
  w: number;
  wPublished: boolean;
  protein: number;
  hydration: [number, number];
  bestFor: string[];
  crowdFavourite: string[];
  note: string;
  bagImage: string;
  logo: string | null;
};

export const FLOUR_DB: FlourEntry[] = [
  // ── Caputo ───────────────────────────────────
  {
    id: 'caputo_pizzeria',
    brand: 'Caputo', name: 'Pizzeria',
    type: '00', country: 'it',
    w: 260, wPublished: true, protein: 12.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: ['neapolitan'],
    note: 'Blue bag. AVPN approved. Most popular Caputo retail product.',
    bagImage: '', logo: null,
  },
  {
    id: 'caputo_cuoco',
    brand: 'Caputo', name: 'Cuoco',
    type: '00', country: 'it',
    w: 310, wPublished: true, protein: 13.0, hydration: [62, 68],
    bestFor: [], crowdFavourite: ['neapolitan', 'newyork'],
    note: 'Red bag. Same flour as Saccorosso professional bag.',
    bagImage: '', logo: null,
  },
  {
    id: 'caputo_saccorosso',
    brand: 'Caputo', name: 'Saccorosso',
    type: '00', country: 'it',
    w: 310, wPublished: true, protein: 13.5, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'Professional large bag version of Cuoco.',
    bagImage: '', logo: null,
  },
  {
    id: 'caputo_nuvola',
    brand: 'Caputo', name: 'Nuvola',
    type: '00', country: 'it',
    w: 270, wPublished: true, protein: 12.5, hydration: [62, 68],
    bestFor: [], crowdFavourite: ['neapolitan'],
    note: 'Tipo 0. Designed for light airy cornicione. High extensibility.',
    bagImage: '', logo: null,
  },
  {
    id: 'caputo_nuvola_super',
    brand: 'Caputo', name: 'Nuvola Super',
    type: '00', country: 'it',
    w: 320, wPublished: true, protein: 13.0, hydration: [64, 70],
    bestFor: [], crowdFavourite: [],
    note: 'Stronger version of Nuvola. Pre-fermented wheat. For biga/poolish.',
    bagImage: '', logo: null,
  },
  {
    id: 'caputo_classica',
    brand: 'Caputo', name: 'Classica',
    type: '00', country: 'it',
    w: 220, wPublished: true, protein: 11.0, hydration: [57, 63],
    bestFor: [], crowdFavourite: [],
    note: 'Weak 00. For quick doughs and pasta. Not for long ferments.',
    bagImage: '', logo: null,
  },
  {
    id: 'caputo_americana',
    brand: 'Caputo', name: 'Americana',
    type: '00', country: 'it',
    w: 340, wPublished: true, protein: 13.5, hydration: [62, 68],
    bestFor: [], crowdFavourite: ['newyork'],
    note: 'With natural malt. Designed for US-style pizza at 500-700°F.',
    bagImage: '', logo: null,
  },
  {
    id: 'caputo_americana_super',
    brand: 'Caputo', name: 'Americana Super',
    type: '00', country: 'it',
    w: 370, wPublished: true, protein: 15.25, hydration: [64, 70],
    bestFor: [], crowdFavourite: [],
    note: 'Highest gluten Caputo flour. NY/Detroit/Sicilian styles.',
    bagImage: '', logo: null,
  },
  {
    id: 'caputo_manitoba',
    brand: 'Caputo', name: 'Manitoba',
    type: 'high_gluten', country: 'it',
    w: 400, wPublished: false, protein: 14.5, hydration: [65, 71],
    bestFor: [], crowdFavourite: [],
    note: 'Blending flour. Adds strength to weaker flour blends.',
    bagImage: '', logo: null,
  },
  {
    id: 'caputo_semola',
    brand: 'Caputo', name: 'Semola Rimacinata',
    type: 'semolina', country: 'it',
    w: 200, wPublished: false, protein: 12.5, hydration: [59, 65],
    bestFor: [], crowdFavourite: [],
    note: 'Remilled durum wheat. Roman pizza, focaccia, dusting.',
    bagImage: '', logo: null,
  },

  // ── 5 Stagioni ───────────────────────────────
  {
    id: 'stagioni_pizza',
    brand: '5 Stagioni', name: 'Pizza',
    type: '00', country: 'it',
    w: 270, wPublished: true, protein: 12.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Classic 5 Stagioni entry-level 00 pizza flour.',
    bagImage: '', logo: null,
  },
  {
    id: 'stagioni_napoletana',
    brand: '5 Stagioni', name: 'Napoletana',
    type: '00', country: 'it',
    w: 300, wPublished: true, protein: 13.5, hydration: [57, 63],
    bestFor: [], crowdFavourite: ['neapolitan'],
    note: 'AVPN approved. W300. Absorption min 55%, stability 10min.',
    bagImage: '', logo: null,
  },
  {
    id: 'stagioni_gold',
    brand: '5 Stagioni', name: 'Gold',
    type: '00', country: 'it',
    w: 380, wPublished: true, protein: 14.0, hydration: [64, 70],
    bestFor: [], crowdFavourite: [],
    note: 'Professional. For long cold ferments 48-96h.',
    bagImage: '', logo: null,
  },
  {
    id: 'stagioni_rossa',
    brand: '5 Stagioni', name: 'Rossa',
    type: '00', country: 'it',
    w: 300, wPublished: true, protein: 13.0, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Strong red bag. 48-72h ferments. Slightly nuttier than Caputo.',
    bagImage: '', logo: null,
  },
  {
    id: 'stagioni_manitoba',
    brand: '5 Stagioni', name: 'Manitoba',
    type: 'high_gluten', country: 'it',
    w: 410, wPublished: false, protein: 14.5, hydration: [65, 71],
    bestFor: [], crowdFavourite: [],
    note: 'For blending to boost weaker flours.',
    bagImage: '', logo: null,
  },

  // ── Petra ────────────────────────────────────
  {
    id: 'petra_5063',
    brand: 'Petra', name: '5063',
    type: '00', country: 'it',
    w: 280, wPublished: false, protein: 13.0, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'AVPN approved. Favorite of Neapolitan pizza makers.',
    bagImage: '', logo: null,
  },
  {
    id: 'petra_5037',
    brand: 'Petra', name: '5037',
    type: '00', country: 'it',
    w: 320, wPublished: false, protein: 13.5, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'Stronger than 5063. Higher hydration and longer fermentation.',
    bagImage: '', logo: null,
  },
  {
    id: 'petra_0102',
    brand: 'Petra', name: '0102 HP',
    type: 'bread', country: 'it',
    w: 300, wPublished: false, protein: 13.0, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'Tipo 1. Stone ground. Partially sprouted wheat. Modern Neapolitan.',
    bagImage: '', logo: null,
  },
  {
    id: 'petra_3',
    brand: 'Petra', name: '3',
    type: 'bread', country: 'it',
    w: 280, wPublished: false, protein: 12.5, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'Stone ground Tipo 1. Versatile for bread and pizza.',
    bagImage: '', logo: null,
  },
  {
    id: 'petra_9',
    brand: 'Petra', name: '9',
    type: 'wholemeal', country: 'it',
    w: 250, wPublished: false, protein: 13.0, hydration: [65, 71],
    bestFor: [], crowdFavourite: [],
    note: 'Whole wheat stone ground. Rich in fiber. Complex flavor.',
    bagImage: '', logo: null,
  },
  {
    id: 'petra_5078',
    brand: 'Petra', name: '5078',
    type: '00', country: 'it',
    w: 300, wPublished: false, protein: 13.0, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'For Teglia Romana, pinsa, crunchy doughs.',
    bagImage: '', logo: null,
  },

  // ── Other Italian ────────────────────────────
  {
    id: 'molino_grassi_organic',
    brand: 'Molino Grassi', name: 'USDA Organic 00',
    type: '00', country: 'it',
    w: 260, wPublished: false, protein: 12.0, hydration: [59, 65],
    bestFor: [], crowdFavourite: [],
    note: 'Organic certified. Common in US organic stores.',
    bagImage: '', logo: null,
  },
  {
    id: 'polselli_classica',
    brand: 'Polselli', name: 'Classica 00',
    type: '00', country: 'it',
    w: 250, wPublished: false, protein: 12.0, hydration: [59, 65],
    bestFor: [], crowdFavourite: ['neapolitan'],
    note: 'Classic Italian 00. Good for most pizza styles.',
    bagImage: '', logo: null,
  },
  {
    id: 'polselli_super',
    brand: 'Polselli', name: 'Super 00',
    type: '00', country: 'it',
    w: 310, wPublished: false, protein: 13.5, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'Strong 00 for long fermentation.',
    bagImage: '', logo: null,
  },
  {
    id: 'polselli_vivace',
    brand: 'Polselli', name: 'Vivace 00',
    type: '00', country: 'it',
    w: 300, wPublished: false, protein: 13.0, hydration: [61, 67],
    bestFor: [], crowdFavourite: [],
    note: 'Popular in US. Good for Napoletana and Romana styles.',
    bagImage: '', logo: null,
  },
  {
    id: 'pivetti_00',
    brand: 'Pivetti', name: 'All Purpose 00',
    type: '00', country: 'it',
    w: 240, wPublished: false, protein: 11.5, hydration: [58, 64],
    bestFor: [], crowdFavourite: [],
    note: 'Versatile Italian 00. Good for pasta and short ferment pizza.',
    bagImage: '', logo: null,
  },
  {
    id: 'dalla_giovanna_magica',
    brand: 'Dalla Giovanna', name: 'Magica 00',
    type: '00', country: 'it',
    w: 280, wPublished: false, protein: 12.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Italian professional brand.',
    bagImage: '', logo: null,
  },
  {
    id: 'molino_marino_rossa',
    brand: 'Molino Marino', name: 'Uniqua Rossa',
    type: '00', country: 'it',
    w: 320, wPublished: false, protein: 14.0, hydration: [63, 69],
    bestFor: [], crowdFavourite: [],
    note: 'Strong Italian stone-milled flour.',
    bagImage: '', logo: null,
  },
  {
    id: 'molino_marino_blu',
    brand: 'Molino Marino', name: 'Uniqua Blu',
    type: '00', country: 'it',
    w: 260, wPublished: false, protein: 12.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Standard 00. Popular in Italian home baking community.',
    bagImage: '', logo: null,
  },
  {
    id: 'agugiaro_figna',
    brand: 'Agugiaro & Figna', name: 'Le 5 Stagioni (parent)',
    type: '00', country: 'it',
    w: 270, wPublished: false, protein: 12.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Parent company of 5 Stagioni.',
    bagImage: '', logo: null,
  },
  {
    id: 'lo_conte_00',
    brand: 'Lo Conte', name: 'Farina 00',
    type: '00', country: 'it',
    w: 240, wPublished: false, protein: 11.5, hydration: [58, 64],
    bestFor: [], crowdFavourite: [],
    note: 'Italian supermarket own brand 00.',
    bagImage: '', logo: null,
  },
  {
    id: 'barilla_00',
    brand: 'Barilla', name: 'Farina 00',
    type: '00', country: 'it',
    w: 220, wPublished: false, protein: 11.0, hydration: [57, 63],
    bestFor: [], crowdFavourite: [],
    note: 'Mass market Italian brand. Available in many Asian supermarkets.',
    bagImage: '', logo: null,
  },
  {
    id: 'de_cecco_semolina',
    brand: 'De Cecco', name: 'Semolato di grano duro',
    type: 'semolina', country: 'it',
    w: 200, wPublished: false, protein: 13.0, hydration: [59, 65],
    bestFor: [], crowdFavourite: [],
    note: 'Common Italian semolina. Available in SEA specialty stores.',
    bagImage: '', logo: null,
  },
  {
    id: 'mulino_casillo_00',
    brand: 'Mulino Casillo', name: 'Farina 00',
    type: '00', country: 'it',
    w: 250, wPublished: false, protein: 12.0, hydration: [59, 65],
    bestFor: [], crowdFavourite: [],
    note: 'Professional Italian mill. Common in SEA restaurant supply.',
    bagImage: '', logo: null,
  },

  // ── French ───────────────────────────────────
  {
    id: 'gmp_t45_gruau',
    brand: 'Grands Moulins de Paris', name: 'T45 Gruau Rouge',
    type: '00', country: 'fr',
    w: 300, wPublished: false, protein: 12.9, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Strong French T45. For croissants, brioches, long-ferment pizza.',
    bagImage: '', logo: null,
  },
  {
    id: 'gmp_t45_violette',
    brand: 'Grands Moulins de Paris', name: 'T45 Violette',
    type: '00', country: 'fr',
    w: 180, wPublished: false, protein: 9.5, hydration: [55, 61],
    bestFor: [], crowdFavourite: [],
    note: 'Weak T45. For pastries, cakes, short-rise doughs.',
    bagImage: '', logo: null,
  },
  {
    id: 'gmp_t55',
    brand: 'Grands Moulins de Paris', name: 'T55 La Finoise',
    type: 'all_purpose', country: 'fr',
    w: 200, wPublished: false, protein: 10.5, hydration: [57, 63],
    bestFor: [], crowdFavourite: [],
    note: 'Standard French T55. All-purpose. Baguettes, boules, brioche.',
    bagImage: '', logo: null,
  },
  {
    id: 'gmp_t65',
    brand: 'Grands Moulins de Paris', name: 'T65 Tradition',
    type: 'bread', country: 'fr',
    w: 220, wPublished: false, protein: 11.0, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'French bread flour. For baguettes de tradition.',
    bagImage: '', logo: null,
  },
  {
    id: 'francine_t45',
    brand: 'Francine', name: 'Farine T45',
    type: '00', country: 'fr',
    w: 170, wPublished: false, protein: 9.5, hydration: [55, 61],
    bestFor: [], crowdFavourite: [],
    note: 'Consumer supermarket T45. Widely available in France.',
    bagImage: '', logo: null,
  },
  {
    id: 'francine_t55',
    brand: 'Francine', name: 'Farine T55',
    type: 'all_purpose', country: 'fr',
    w: 180, wPublished: false, protein: 10.0, hydration: [57, 63],
    bestFor: [], crowdFavourite: [],
    note: 'Most common French supermarket flour. Standard all-purpose.',
    bagImage: '', logo: null,
  },
  {
    id: 'francine_t65',
    brand: 'Francine', name: 'Farine T65',
    type: 'bread', country: 'fr',
    w: 200, wPublished: false, protein: 10.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'French bread flour. Common in French supermarkets.',
    bagImage: '', logo: null,
  },
  {
    id: 'foricher_t45',
    brand: 'Foricher', name: 'Gruau T45 Bagatelle',
    type: '00', country: 'fr',
    w: 300, wPublished: false, protein: 13.0, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Label Rouge. CRC certified. For viennoiserie and pizza.',
    bagImage: '', logo: null,
  },
  {
    id: 'foricher_t65',
    brand: 'Foricher', name: 'T65 Tradition Bagatelle',
    type: 'bread', country: 'fr',
    w: 220, wPublished: false, protein: 11.0, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'Artisan T65. Label Rouge. For baguettes de tradition.',
    bagImage: '', logo: null,
  },
  {
    id: 'viron_retrodor',
    brand: 'Minoteries Viron', name: 'Rétrodor T65',
    type: 'bread', country: 'fr',
    w: 230, wPublished: false, protein: 11.5, hydration: [63, 69],
    bestFor: [], crowdFavourite: [],
    note: 'Premium French baker\'s flour. Used by top Parisian boulangeries.',
    bagImage: '', logo: null,
  },
  {
    id: 'colagne_t65',
    brand: 'Moulin de Colagne', name: 'T65 Tradition',
    type: 'bread', country: 'fr',
    w: 220, wPublished: false, protein: 11.0, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'Regional French mill. Good artisan bread flour.',
    bagImage: '', logo: null,
  },
  {
    id: 'moulins_bourgeois',
    brand: 'Moulins Bourgeois', name: 'Farine de Tradition',
    type: 'bread', country: 'fr',
    w: 240, wPublished: false, protein: 11.5, hydration: [63, 69],
    bestFor: [], crowdFavourite: [],
    note: 'Premium French traditional flour. Artisan bakers.',
    bagImage: '', logo: null,
  },
  {
    id: 'carrefour_t45',
    brand: 'Carrefour', name: 'Farine de blé T45',
    type: '00', country: 'fr',
    w: 160, wPublished: false, protein: 9.0, hydration: [55, 61],
    bestFor: [], crowdFavourite: [],
    note: 'French supermarket own brand T45. Weak flour.',
    bagImage: '', logo: null,
  },
  {
    id: 'carrefour_t55',
    brand: 'Carrefour', name: 'Farine de blé T55',
    type: 'all_purpose', country: 'fr',
    w: 175, wPublished: false, protein: 10.0, hydration: [57, 63],
    bestFor: [], crowdFavourite: [],
    note: 'Standard French supermarket T55.',
    bagImage: '', logo: null,
  },
  {
    id: 'carrefour_pizza',
    brand: 'Carrefour', name: 'Farine spéciale pizza',
    type: '00', country: 'fr',
    w: 220, wPublished: false, protein: 11.0, hydration: [58, 64],
    bestFor: [], crowdFavourite: [],
    note: 'French supermarket pizza-specific flour.',
    bagImage: '', logo: null,
  },
  {
    id: 'leclerc_t55',
    brand: 'Marque Repère', name: 'Farine T55',
    type: 'all_purpose', country: 'fr',
    w: 170, wPublished: false, protein: 9.5, hydration: [56, 62],
    bestFor: [], crowdFavourite: [],
    note: 'E.Leclerc own brand flour.',
    bagImage: '', logo: null,
  },

  // ── UK ───────────────────────────────────────
  {
    id: 'shipton_t55',
    brand: 'Shipton Mill', name: 'T55 French Flour',
    type: 'all_purpose', country: 'uk',
    w: 200, wPublished: false, protein: 10.5, hydration: [59, 65],
    bestFor: [], crowdFavourite: [],
    note: 'French-style T55 milled or imported by UK\'s Shipton Mill.',
    bagImage: '', logo: null,
  },
  {
    id: 'shipton_strong',
    brand: 'Shipton Mill', name: 'Strong White Bread Flour',
    type: 'bread', country: 'uk',
    w: 250, wPublished: false, protein: 13.0, hydration: [61, 67],
    bestFor: [], crowdFavourite: [],
    note: 'Premium UK bread flour.',
    bagImage: '', logo: null,
  },
  {
    id: 'shipton_t45',
    brand: 'Shipton Mill', name: 'T45 Gruau',
    type: '00', country: 'uk',
    w: 290, wPublished: false, protein: 12.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Strong T45 for croissants and long-ferment pizza.',
    bagImage: '', logo: null,
  },
  {
    id: 'marriages_strong',
    brand: 'Marriages', name: 'Strong White Bread Flour',
    type: 'bread', country: 'uk',
    w: 250, wPublished: true, protein: 13.4, hydration: [61, 67],
    bestFor: [], crowdFavourite: [],
    note: 'UK artisan mill. Good reputation with sourdough bakers.',
    bagImage: '', logo: null,
  },
  {
    id: 'doves_organic_strong',
    brand: 'Doves Farm', name: 'Organic Strong White Bread Flour',
    type: 'bread', country: 'uk',
    w: 240, wPublished: false, protein: 13.0, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Organic UK flour. Common in UK supermarkets.',
    bagImage: '', logo: null,
  },
  {
    id: 'allinson_bread',
    brand: 'Allinson', name: 'Bread Flour Strong White',
    type: 'bread', country: 'uk',
    w: 230, wPublished: false, protein: 12.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'UK supermarket bread flour. Widely available.',
    bagImage: '', logo: null,
  },
  {
    id: 'mcdougalls_bread',
    brand: 'McDougalls', name: 'Strong White Bread Flour',
    type: 'bread', country: 'uk',
    w: 230, wPublished: false, protein: 12.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'UK supermarket bread flour.',
    bagImage: '', logo: null,
  },
  {
    id: 'waitrose_bread',
    brand: 'Waitrose', name: 'Strong White Bread Flour',
    type: 'bread', country: 'uk',
    w: 230, wPublished: false, protein: 12.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'UK supermarket own brand bread flour.',
    bagImage: '', logo: null,
  },

  // ── US ───────────────────────────────────────
  {
    id: 'ka_ap',
    brand: 'King Arthur', name: 'All-Purpose Flour',
    type: 'all_purpose', country: 'us',
    w: 200, wPublished: true, protein: 11.7, hydration: [59, 65],
    bestFor: [], crowdFavourite: [],
    note: 'Highest protein US all-purpose. Good for pizza and bread.',
    bagImage: '', logo: null,
  },
  {
    id: 'ka_bread',
    brand: 'King Arthur', name: 'Bread Flour',
    type: 'bread', country: 'us',
    w: 260, wPublished: true, protein: 12.7, hydration: [61, 67],
    bestFor: [], crowdFavourite: ['newyork'],
    note: 'Best US supermarket bread flour. Consistent protein.',
    bagImage: '', logo: null,
  },
  {
    id: 'ka_00',
    brand: 'King Arthur', name: '00 Pizza Flour',
    type: '00', country: 'us',
    w: 200, wPublished: false, protein: 11.5, hydration: [58, 64],
    bestFor: [], crowdFavourite: [],
    note: 'US-milled 00. Blend of soft and hard wheat. Weaker than Italian 00.',
    bagImage: '', logo: null,
  },
  {
    id: 'ka_sir_galahad',
    brand: 'King Arthur', name: 'Sir Galahad',
    type: 'all_purpose', country: 'us',
    w: 200, wPublished: false, protein: 11.7, hydration: [59, 65],
    bestFor: [], crowdFavourite: [],
    note: 'Professional/foodservice version of KA AP. 100% hard red winter wheat.',
    bagImage: '', logo: null,
  },
  {
    id: 'ka_sir_lancelot',
    brand: 'King Arthur', name: 'Sir Lancelot',
    type: '00', country: 'us',
    w: 310, wPublished: false, protein: 14.2, hydration: [64, 70],
    bestFor: [], crowdFavourite: [],
    note: 'High gluten professional flour. For bagels, NY pizza.',
    bagImage: '', logo: null,
  },
  {
    id: 'ka_organic_ap',
    brand: 'King Arthur', name: 'Organic All Purpose',
    type: 'all_purpose', country: 'us',
    w: 195, wPublished: false, protein: 11.0, hydration: [58, 64],
    bestFor: [], crowdFavourite: [],
    note: 'Organic version of KA AP.',
    bagImage: '', logo: null,
  },
  {
    id: 'gold_medal_ap',
    brand: 'Gold Medal', name: 'All-Purpose Flour',
    type: 'all_purpose', country: 'us',
    w: 170, wPublished: false, protein: 10.5, hydration: [57, 63],
    bestFor: [], crowdFavourite: [],
    note: 'Most common US supermarket flour. Lower protein than KA.',
    bagImage: '', logo: null,
  },
  {
    id: 'gold_medal_bread',
    brand: 'Gold Medal', name: 'Bread Flour',
    type: 'bread', country: 'us',
    w: 240, wPublished: false, protein: 12.3, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Standard US bread flour.',
    bagImage: '', logo: null,
  },
  {
    id: 'gold_medal_harvest',
    brand: 'Gold Medal', name: 'Harvest King / Better for Bread',
    type: 'bread', country: 'us',
    w: 240, wPublished: false, protein: 12.0, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Hard winter wheat. Popular with home bread bakers.',
    bagImage: '', logo: null,
  },
  {
    id: 'gold_medal_full_strength',
    brand: 'Gold Medal', name: 'Full Strength',
    type: '00', country: 'us',
    w: 270, wPublished: false, protein: 12.6, hydration: [61, 67],
    bestFor: [], crowdFavourite: [],
    note: 'Spring wheat. Professional grade. For bagels and pizza.',
    bagImage: '', logo: null,
  },
  {
    id: 'bobs_artisan_bread',
    brand: "Bob's Red Mill", name: 'Artisan Bread Flour',
    type: 'bread', country: 'us',
    w: 250, wPublished: true, protein: 13.0, hydration: [61, 67],
    bestFor: [], crowdFavourite: [],
    note: 'With malted barley. Popular US artisan bread flour.',
    bagImage: '', logo: null,
  },
  {
    id: 'bobs_ap',
    brand: "Bob's Red Mill", name: 'All-Purpose Flour',
    type: 'all_purpose', country: 'us',
    w: 185, wPublished: false, protein: 11.0, hydration: [58, 64],
    bestFor: [], crowdFavourite: [],
    note: 'Unbleached. Common in US natural food stores.',
    bagImage: '', logo: null,
  },
  {
    id: 'pillsbury_ap',
    brand: 'Pillsbury', name: 'All-Purpose Flour',
    type: 'all_purpose', country: 'us',
    w: 165, wPublished: false, protein: 10.5, hydration: [57, 63],
    bestFor: [], crowdFavourite: [],
    note: 'Standard US supermarket flour.',
    bagImage: '', logo: null,
  },
  {
    id: 'pillsbury_bread',
    brand: 'Pillsbury', name: 'Bread Flour',
    type: 'bread', country: 'us',
    w: 230, wPublished: false, protein: 12.0, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Standard US bread flour.',
    bagImage: '', logo: null,
  },
  {
    id: 'central_high_mountain',
    brand: 'Central Milling', name: 'High Mountain',
    type: 'bread', country: 'us',
    w: 270, wPublished: false, protein: 13.5, hydration: [63, 69],
    bestFor: [], crowdFavourite: [],
    note: 'Premium US artisan flour. Favored by sourdough bakers.',
    bagImage: '', logo: null,
  },
  {
    id: 'central_00',
    brand: 'Central Milling', name: 'Type 00 Normal',
    type: '00', country: 'us',
    w: 240, wPublished: false, protein: 11.5, hydration: [59, 65],
    bestFor: [], crowdFavourite: [],
    note: 'US-milled 00. More accessible than imported.',
    bagImage: '', logo: null,
  },
  {
    id: 'central_type85',
    brand: 'Central Milling', name: 'Organic Type 85',
    type: 'bread', country: 'us',
    w: 240, wPublished: false, protein: 12.5, hydration: [67, 73],
    bestFor: [], crowdFavourite: [],
    note: 'High extraction. Excellent for sourdough and rustic loaves.',
    bagImage: '', logo: null,
  },
  {
    id: 'giustos_bread',
    brand: "Giusto's", name: 'Bread Flour',
    type: 'bread', country: 'us',
    w: 250, wPublished: false, protein: 12.5, hydration: [61, 67],
    bestFor: [], crowdFavourite: [],
    note: 'Premium California mill. Good for artisan bread.',
    bagImage: '', logo: null,
  },
  {
    id: 'giustos_high_perf',
    brand: "Giusto's", name: 'High Performance Bread Flour',
    type: '00', country: 'us',
    w: 290, wPublished: false, protein: 14.5, hydration: [64, 70],
    bestFor: [], crowdFavourite: [],
    note: 'Very high protein. For NY-style and long ferment applications.',
    bagImage: '', logo: null,
  },
  {
    id: 'white_lily_ap',
    brand: 'White Lily', name: 'All Purpose Flour',
    type: 'all_purpose', country: 'us',
    w: 120, wPublished: false, protein: 8.0, hydration: [53, 59],
    bestFor: [], crowdFavourite: [],
    note: 'Very soft Southern wheat. Not suitable for pizza/bread.',
    bagImage: '', logo: null,
  },
  {
    id: 'white_lily_bread',
    brand: 'White Lily', name: 'Bread Flour',
    type: 'bread', country: 'us',
    w: 230, wPublished: false, protein: 11.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Finely ground. Similar protein to KA AP. Lighter texture.',
    bagImage: '', logo: null,
  },
  {
    id: 'hodgson_bread',
    brand: 'Hodgson Mill', name: 'Best for Bread',
    type: 'bread', country: 'us',
    w: 230, wPublished: false, protein: 12.0, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'US bread flour.',
    bagImage: '', logo: null,
  },

  // ── Canada ───────────────────────────────────
  {
    id: 'robin_hood_ap',
    brand: 'Robin Hood', name: 'All Purpose Flour',
    type: 'all_purpose', country: 'ca',
    w: 230, wPublished: false, protein: 13.3, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Canadian wheat. Higher protein than US AP flour.',
    bagImage: '', logo: null,
  },
  {
    id: 'robin_hood_bread',
    brand: 'Robin Hood', name: 'Best for Bread',
    type: 'bread', country: 'ca',
    w: 260, wPublished: false, protein: 13.3, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'Canadian bread flour. High protein Canadian wheat.',
    bagImage: '', logo: null,
  },
  {
    id: 'five_roses_ap',
    brand: 'Five Roses', name: 'All Purpose Flour',
    type: 'all_purpose', country: 'ca',
    w: 230, wPublished: false, protein: 13.3, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Canadian flour. High protein like Robin Hood.',
    bagImage: '', logo: null,
  },
  {
    id: 'anitas_ap',
    brand: "Anita's", name: 'Organic All Purpose Flour',
    type: 'all_purpose', country: 'ca',
    w: 220, wPublished: false, protein: 12.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Premium Canadian organic flour.',
    bagImage: '', logo: null,
  },

  // ── Australia ────────────────────────────────
  {
    id: 'wholegrain_milling',
    brand: 'Wholegrain Milling', name: 'Premium Bakers White High Protein',
    type: 'bread', country: 'au',
    w: 260, wPublished: false, protein: 13.5, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'Australian organic. Available in Singapore via specialty stores.',
    bagImage: '', logo: null,
  },
  {
    id: 'coles_plain',
    brand: 'Coles', name: 'Plain Flour',
    type: 'all_purpose', country: 'au',
    w: 175, wPublished: false, protein: 10.0, hydration: [57, 63],
    bestFor: [], crowdFavourite: [],
    note: 'Australian supermarket own brand.',
    bagImage: '', logo: null,
  },
  {
    id: 'woolworths_bread',
    brand: 'Woolworths', name: 'Bread and Pizza Flour',
    type: 'bread', country: 'au',
    w: 240, wPublished: false, protein: 12.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Australian supermarket bread flour.',
    bagImage: '', logo: null,
  },
  {
    id: 'defiance_bread',
    brand: 'Defiance', name: 'Bakers Flour',
    type: 'bread', country: 'au',
    w: 250, wPublished: false, protein: 13.0, hydration: [61, 67],
    bestFor: [], crowdFavourite: [],
    note: 'Australian commercial bakers flour.',
    bagImage: '', logo: null,
  },

  // ── Singapore ────────────────────────────────
  {
    id: 'prima_bread',
    brand: 'Prima', name: 'Bread Flour',
    type: 'bread', country: 'sg',
    w: 240, wPublished: false, protein: 12.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Leading Singapore flour brand. Available at FairPrice and most supermarkets.',
    bagImage: '', logo: null,
  },
  {
    id: 'prima_plain',
    brand: 'Prima', name: 'Plain Flour',
    type: 'all_purpose', country: 'sg',
    w: 170, wPublished: false, protein: 9.5, hydration: [57, 63],
    bestFor: [], crowdFavourite: [],
    note: 'Standard Singapore all-purpose flour.',
    bagImage: '', logo: null,
  },
  {
    id: 'prima_superior',
    brand: 'Prima', name: 'Superior Bread Flour',
    type: 'bread', country: 'sg',
    w: 260, wPublished: false, protein: 13.5, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'High protein. For Japanese-style milk bread and buns.',
    bagImage: '', logo: null,
  },
  {
    id: 'prima_clover',
    brand: 'Prima', name: 'Clover Bread Flour',
    type: 'bread', country: 'sg',
    w: 250, wPublished: false, protein: 12.8, hydration: [61, 67],
    bestFor: [], crowdFavourite: [],
    note: '12.8% protein. Common in Singapore commercial bakeries.',
    bagImage: '', logo: null,
  },
  {
    id: 'prima_artisan',
    brand: 'Prima', name: 'Artisan Bread Flour',
    type: 'bread', country: 'sg',
    w: 260, wPublished: false, protein: 13.0, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'For ciabatta and artisan loaves. Available in Singapore.',
    bagImage: '', logo: null,
  },
  {
    id: 'bake_king_bread',
    brand: 'Bake King', name: 'Bread Flour',
    type: 'bread', country: 'sg',
    w: 240, wPublished: false, protein: 12.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Singapore brand. Available at Phoon Huat and baking stores.',
    bagImage: '', logo: null,
  },
  {
    id: 'bake_king_plain',
    brand: 'Bake King', name: 'Plain Flour',
    type: 'all_purpose', country: 'sg',
    w: 165, wPublished: false, protein: 9.5, hydration: [57, 63],
    bestFor: [], crowdFavourite: [],
    note: 'Common Singapore household flour.',
    bagImage: '', logo: null,
  },
  {
    id: 'phoon_huat_bread',
    brand: 'Phoon Huat', name: 'Super Baker Bread Flour',
    type: 'bread', country: 'sg',
    w: 250, wPublished: false, protein: 13.0, hydration: [61, 67],
    bestFor: [], crowdFavourite: [],
    note: 'Available at Phoon Huat baking supply stores in Singapore.',
    bagImage: '', logo: null,
  },
  {
    id: 'sun_hong_bread',
    brand: 'Sun Hong', name: 'High Protein Bread Flour',
    type: 'bread', country: 'sg',
    w: 240, wPublished: false, protein: 12.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Singapore commercial bakery brand.',
    bagImage: '', logo: null,
  },

  // ── Malaysia ─────────────────────────────────
  {
    id: 'bagus_bread',
    brand: 'Bagus', name: 'Bread Flour',
    type: 'bread', country: 'my',
    w: 240, wPublished: false, protein: 12.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Malaysian brand. Available in Singapore and Malaysia.',
    bagImage: '', logo: null,
  },
  {
    id: 'payless_bread',
    brand: 'Payless', name: 'Bread Flour',
    type: 'bread', country: 'my',
    w: 235, wPublished: false, protein: 12.0, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Malaysian supermarket bread flour.',
    bagImage: '', logo: null,
  },
  {
    id: 'renown_bread',
    brand: 'Renown', name: 'Bread Flour',
    type: 'bread', country: 'my',
    w: 240, wPublished: false, protein: 12.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Malaysian bread flour. Common in SEA.',
    bagImage: '', logo: null,
  },

  // ── Japan ────────────────────────────────────
  {
    id: 'nisshin_camellia',
    brand: 'Nisshin', name: 'Bread Flour',
    type: 'bread', country: 'jp',
    w: 260, wPublished: true, protein: 13.5, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'Japanese premium bread flour. Popular in SEA Asian bakeries.',
    bagImage: '', logo: null,
  },
  {
    id: 'nisshin_violet',
    brand: 'Nisshin', name: 'Violet All Purpose',
    type: 'all_purpose', country: 'jp',
    w: 180, wPublished: false, protein: 10.0, hydration: [57, 63],
    bestFor: [], crowdFavourite: [],
    note: 'Japanese AP flour. Widely available in Asian supermarkets.',
    bagImage: '', logo: null,
  },
  {
    id: 'showa_camellia',
    brand: 'Showa', name: 'Camellia Bread Flour',
    type: 'bread', country: 'jp',
    w: 260, wPublished: false, protein: 13.5, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'Top Japanese bread flour. Used in many SEA bakeries.',
    bagImage: '', logo: null,
  },
  {
    id: 'showa_lys_dor',
    brand: 'Showa', name: "Lys d'Or",
    type: '00', country: 'jp',
    w: 300, wPublished: false, protein: 14.5, hydration: [64, 70],
    bestFor: [], crowdFavourite: [],
    note: 'Very high gluten Japanese flour. For chewy NY-style pizza.',
    bagImage: '', logo: null,
  },

  // ── Generic ──────────────────────────────────
  {
    id: 'generic_00',
    brand: 'Generic', name: 'Pizza 00 Flour',
    type: '00', country: 'it',
    w: 250, wPublished: false, protein: 12.0, hydration: [59, 65],
    bestFor: [], crowdFavourite: [],
    note: 'Generic Italian 00 pizza flour estimate.',
    bagImage: '', logo: null,
  },
  {
    id: 'generic_strong00',
    brand: 'Generic', name: 'Strong 00 / High Protein 00',
    type: '00', country: 'it',
    w: 300, wPublished: false, protein: 13.5, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'Generic strong 00 estimate.',
    bagImage: '', logo: null,
  },
  {
    id: 'generic_bread',
    brand: 'Generic', name: 'Bread Flour / T65',
    type: 'bread', country: 'us',
    w: 230, wPublished: false, protein: 12.5, hydration: [61, 67],
    bestFor: [], crowdFavourite: [],
    note: 'Generic bread flour estimate.',
    bagImage: '', logo: null,
  },
  {
    id: 'generic_ap',
    brand: 'Generic', name: 'All Purpose / T55',
    type: 'all_purpose', country: 'us',
    w: 160, wPublished: false, protein: 10.5, hydration: [57, 63],
    bestFor: [], crowdFavourite: [],
    note: 'Generic all-purpose estimate.',
    bagImage: '', logo: null,
  },
  {
    id: 'generic_manitoba',
    brand: 'Generic', name: 'Manitoba Flour',
    type: 'high_gluten', country: 'it',
    w: 380, wPublished: false, protein: 14.5, hydration: [65, 71],
    bestFor: [], crowdFavourite: [],
    note: 'Generic Manitoba estimate. Very strong blending flour.',
    bagImage: '', logo: null,
  },
  {
    id: 'generic_semolina',
    brand: 'Generic', name: 'Semolina / Semola',
    type: 'semolina', country: 'it',
    w: 200, wPublished: false, protein: 13.0, hydration: [59, 65],
    bestFor: [], crowdFavourite: [],
    note: 'Generic semolina estimate.',
    bagImage: '', logo: null,
  },
  {
    id: 'generic_wholemeal',
    brand: 'Generic', name: 'Whole Wheat / Wholemeal',
    type: 'wholemeal', country: 'us',
    w: 220, wPublished: false, protein: 13.0, hydration: [65, 71],
    bestFor: [], crowdFavourite: [],
    note: 'Generic whole wheat estimate.',
    bagImage: '', logo: null,
  },
  {
    id: 'generic_rye',
    brand: 'Generic', name: 'Rye Flour / Seigle',
    type: 'rye', country: 'de',
    w: 150, wPublished: false, protein: 8.0, hydration: [72, 78],
    bestFor: [], crowdFavourite: [],
    note: 'Generic rye flour estimate. High enzyme activity.',
    bagImage: '', logo: null,
  },
];
