export type FlourEntry = {
  id: string;
  brand: string;
  name: string;
  type: '00' | '0' | '1' | '2' | 'T45' | 'T55' | 'T65' | 'T80'
      | 'T110' | 'T150' | 'bread' | 'all_purpose' | 'high_gluten'
      | 'wholemeal' | 'rye' | 'spelt' | 'semolina';
  country: 'it' | 'fr' | 'uk' | 'us' | 'ca' | 'sg' | 'au' | 'de'
         | 'jp' | 'kr' | 'cn' | 'in' | 'th' | 'id' | 'my' | 'ph'
         | 'vn' | 'br' | 'mx' | 'ar' | 'se' | 'fi' | 'no' | 'nl'
         | 'pl' | 'at';
  w: number;
  wPublished: boolean;
  protein: number;
  hydration: [number, number];
  bestFor: string[];
  crowdFavourite: string[];
  note: string;
  bagImage: string;
  logo: string | null;
};

export const FLOUR_DB: FlourEntry[] = [
  // ── Caputo ───────────────────────────────────
  {
    id: 'caputo_pizzeria',
    brand: 'Caputo', name: 'Pizzeria',
    type: '00', country: 'it',
    w: 260, wPublished: true, protein: 12.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: ['neapolitan'],
    note: 'Blue bag. AVPN approved. Most popular Caputo retail product.',
    bagImage: '', logo: null,
  },
  {
    id: 'caputo_cuoco',
    brand: 'Caputo', name: 'Cuoco',
    type: '00', country: 'it',
    w: 310, wPublished: true, protein: 13.0, hydration: [62, 68],
    bestFor: [], crowdFavourite: ['neapolitan', 'newyork'],
    note: 'Red bag. Same flour as Saccorosso professional bag.',
    bagImage: '', logo: null,
  },
  {
    id: 'caputo_saccorosso',
    brand: 'Caputo', name: 'Saccorosso',
    type: '00', country: 'it',
    w: 310, wPublished: true, protein: 13.5, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'Professional large bag version of Cuoco.',
    bagImage: '', logo: null,
  },
  {
    id: 'caputo_nuvola',
    brand: 'Caputo', name: 'Nuvola',
    type: '00', country: 'it',
    w: 270, wPublished: true, protein: 12.5, hydration: [62, 68],
    bestFor: [], crowdFavourite: ['neapolitan'],
    note: 'Tipo 0. Designed for light airy cornicione. High extensibility.',
    bagImage: '', logo: null,
  },
  {
    id: 'caputo_nuvola_super',
    brand: 'Caputo', name: 'Nuvola Super',
    type: '00', country: 'it',
    w: 320, wPublished: true, protein: 13.0, hydration: [64, 70],
    bestFor: [], crowdFavourite: [],
    note: 'Stronger version of Nuvola. Pre-fermented wheat. For biga/poolish.',
    bagImage: '', logo: null,
  },
  {
    id: 'caputo_classica',
    brand: 'Caputo', name: 'Classica',
    type: '00', country: 'it',
    w: 220, wPublished: true, protein: 11.0, hydration: [57, 63],
    bestFor: [], crowdFavourite: [],
    note: 'Weak 00. For quick doughs and pasta. Not for long ferments.',
    bagImage: '', logo: null,
  },
  {
    id: 'caputo_americana',
    brand: 'Caputo', name: 'Americana',
    type: '00', country: 'it',
    w: 340, wPublished: true, protein: 13.5, hydration: [62, 68],
    bestFor: [], crowdFavourite: ['newyork'],
    note: 'With natural malt. Designed for US-style pizza at 500-700°F.',
    bagImage: '', logo: null,
  },
  {
    id: 'caputo_americana_super',
    brand: 'Caputo', name: 'Americana Super',
    type: '00', country: 'it',
    w: 370, wPublished: true, protein: 15.25, hydration: [64, 70],
    bestFor: [], crowdFavourite: [],
    note: 'Highest gluten Caputo flour. NY/Detroit/Sicilian styles.',
    bagImage: '', logo: null,
  },
  {
    id: 'caputo_manitoba',
    brand: 'Caputo', name: 'Manitoba',
    type: 'high_gluten', country: 'it',
    w: 400, wPublished: false, protein: 14.5, hydration: [65, 71],
    bestFor: [], crowdFavourite: [],
    note: 'Blending flour. Adds strength to weaker flour blends.',
    bagImage: '', logo: null,
  },
  {
    id: 'caputo_semola',
    brand: 'Caputo', name: 'Semola Rimacinata',
    type: 'semolina', country: 'it',
    w: 200, wPublished: false, protein: 12.5, hydration: [59, 65],
    bestFor: [], crowdFavourite: [],
    note: 'Remilled durum wheat. Roman pizza, focaccia, dusting.',
    bagImage: '', logo: null,
  },

  // ── 5 Stagioni ───────────────────────────────
  {
    id: 'stagioni_pizza',
    brand: '5 Stagioni', name: 'Pizza',
    type: '00', country: 'it',
    w: 270, wPublished: true, protein: 12.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Classic 5 Stagioni entry-level 00 pizza flour.',
    bagImage: '', logo: null,
  },
  {
    id: 'stagioni_napoletana',
    brand: '5 Stagioni', name: 'Napoletana',
    type: '00', country: 'it',
    w: 300, wPublished: true, protein: 13.5, hydration: [57, 63],
    bestFor: [], crowdFavourite: ['neapolitan'],
    note: 'AVPN approved. W300. Absorption min 55%, stability 10min.',
    bagImage: '', logo: null,
  },
  {
    id: 'stagioni_gold',
    brand: '5 Stagioni', name: 'Gold',
    type: '00', country: 'it',
    w: 380, wPublished: true, protein: 14.0, hydration: [64, 70],
    bestFor: [], crowdFavourite: [],
    note: 'Professional. For long cold ferments 48-96h.',
    bagImage: '', logo: null,
  },
  {
    id: 'stagioni_rossa',
    brand: '5 Stagioni', name: 'Rossa',
    type: '00', country: 'it',
    w: 300, wPublished: true, protein: 13.0, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Strong red bag. 48-72h ferments. Slightly nuttier than Caputo.',
    bagImage: '', logo: null,
  },
  {
    id: 'stagioni_manitoba',
    brand: '5 Stagioni', name: 'Manitoba',
    type: 'high_gluten', country: 'it',
    w: 410, wPublished: false, protein: 14.5, hydration: [65, 71],
    bestFor: [], crowdFavourite: [],
    note: 'For blending to boost weaker flours.',
    bagImage: '', logo: null,
  },
  {
    id: 'stagioni_superiore',
    brand: '5 Stagioni', name: 'Superiore',
    type: '00', country: 'it',
    w: 320, wPublished: true, protein: 13.5, hydration: [62, 68],
    bestFor: [], crowdFavourite: ['neapolitan', 'newyork'],
    note: 'Professional-grade 00. Strong enough for long cold ferments and NY-style.',
    bagImage: '', logo: null,
  },

  // ── Petra ────────────────────────────────────
  {
    id: 'petra_5063',
    brand: 'Petra', name: '5063',
    type: '00', country: 'it',
    w: 280, wPublished: false, protein: 13.0, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'AVPN approved. Favorite of Neapolitan pizza makers.',
    bagImage: '', logo: null,
  },
  {
    id: 'petra_5037',
    brand: 'Petra', name: '5037',
    type: '00', country: 'it',
    w: 320, wPublished: false, protein: 13.5, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'Stronger than 5063. Higher hydration and longer fermentation.',
    bagImage: '', logo: null,
  },
  {
    id: 'petra_0102',
    brand: 'Petra', name: '0102 HP',
    type: 'bread', country: 'it',
    w: 300, wPublished: false, protein: 13.0, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'Tipo 1. Stone ground. Partially sprouted wheat. Modern Neapolitan.',
    bagImage: '', logo: null,
  },
  {
    id: 'petra_3',
    brand: 'Petra', name: '3',
    type: 'bread', country: 'it',
    w: 280, wPublished: false, protein: 12.5, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'Stone ground Tipo 1. Versatile for bread and pizza.',
    bagImage: '', logo: null,
  },
  {
    id: 'petra_9',
    brand: 'Petra', name: '9',
    type: 'wholemeal', country: 'it',
    w: 250, wPublished: false, protein: 13.0, hydration: [65, 71],
    bestFor: [], crowdFavourite: [],
    note: 'Whole wheat stone ground. Rich in fiber. Complex flavor.',
    bagImage: '', logo: null,
  },
  {
    id: 'petra_5078',
    brand: 'Petra', name: '5078',
    type: '00', country: 'it',
    w: 300, wPublished: false, protein: 13.0, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'For Teglia Romana, pinsa, crunchy doughs.',
    bagImage: '', logo: null,
  },

  // ── Other Italian ────────────────────────────
  {
    id: 'molino_grassi_organic',
    brand: 'Molino Grassi', name: 'USDA Organic 00',
    type: '00', country: 'it',
    w: 260, wPublished: false, protein: 12.0, hydration: [59, 65],
    bestFor: [], crowdFavourite: [],
    note: 'Organic certified. Common in US organic stores.',
    bagImage: '', logo: null,
  },
  {
    id: 'polselli_classica',
    brand: 'Polselli', name: 'Classica 00',
    type: '00', country: 'it',
    w: 250, wPublished: false, protein: 12.0, hydration: [59, 65],
    bestFor: [], crowdFavourite: ['neapolitan'],
    note: 'Classic Italian 00. Good for most pizza styles.',
    bagImage: '', logo: null,
  },
  {
    id: 'polselli_super',
    brand: 'Polselli', name: 'Super 00',
    type: '00', country: 'it',
    w: 310, wPublished: false, protein: 13.5, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'Strong 00 for long fermentation.',
    bagImage: '', logo: null,
  },
  {
    id: 'polselli_vivace',
    brand: 'Polselli', name: 'Vivace 00',
    type: '00', country: 'it',
    w: 300, wPublished: false, protein: 13.0, hydration: [61, 67],
    bestFor: [], crowdFavourite: [],
    note: 'Popular in US. Good for Napoletana and Romana styles.',
    bagImage: '', logo: null,
  },
  {
    id: 'pivetti_00',
    brand: 'Pivetti', name: 'All Purpose 00',
    type: '00', country: 'it',
    w: 240, wPublished: false, protein: 11.5, hydration: [58, 64],
    bestFor: [], crowdFavourite: [],
    note: 'Versatile Italian 00. Good for pasta and short ferment pizza.',
    bagImage: '', logo: null,
  },
  {
    id: 'dalla_giovanna_magica',
    brand: 'Dalla Giovanna', name: 'Magica 00',
    type: '00', country: 'it',
    w: 280, wPublished: false, protein: 12.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Italian professional brand.',
    bagImage: '', logo: null,
  },
  {
    id: 'molino_marino_rossa',
    brand: 'Molino Marino', name: 'Uniqua Rossa',
    type: '00', country: 'it',
    w: 320, wPublished: false, protein: 14.0, hydration: [63, 69],
    bestFor: [], crowdFavourite: [],
    note: 'Strong Italian stone-milled flour.',
    bagImage: '', logo: null,
  },
  {
    id: 'molino_marino_blu',
    brand: 'Molino Marino', name: 'Uniqua Blu',
    type: '00', country: 'it',
    w: 260, wPublished: false, protein: 12.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Standard 00. Popular in Italian home baking community.',
    bagImage: '', logo: null,
  },
  {
    id: 'agugiaro_figna',
    brand: 'Agugiaro & Figna', name: 'Le 5 Stagioni (parent)',
    type: '00', country: 'it',
    w: 270, wPublished: false, protein: 12.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Parent company of 5 Stagioni.',
    bagImage: '', logo: null,
  },
  {
    id: 'lo_conte_00',
    brand: 'Lo Conte', name: 'Farina 00',
    type: '00', country: 'it',
    w: 240, wPublished: false, protein: 11.5, hydration: [58, 64],
    bestFor: [], crowdFavourite: [],
    note: 'Italian supermarket own brand 00.',
    bagImage: '', logo: null,
  },
  {
    id: 'barilla_00',
    brand: 'Barilla', name: 'Farina 00',
    type: '00', country: 'it',
    w: 220, wPublished: false, protein: 11.0, hydration: [57, 63],
    bestFor: [], crowdFavourite: [],
    note: 'Mass market Italian brand. Available in many Asian supermarkets.',
    bagImage: '', logo: null,
  },
  {
    id: 'de_cecco_semolina',
    brand: 'De Cecco', name: 'Semolato di grano duro',
    type: 'semolina', country: 'it',
    w: 200, wPublished: false, protein: 13.0, hydration: [59, 65],
    bestFor: [], crowdFavourite: [],
    note: 'Common Italian semolina. Available in SEA specialty stores.',
    bagImage: '', logo: null,
  },
  {
    id: 'mulino_casillo_00',
    brand: 'Mulino Casillo', name: 'Farina 00',
    type: '00', country: 'it',
    w: 250, wPublished: false, protein: 12.0, hydration: [59, 65],
    bestFor: [], crowdFavourite: [],
    note: 'Professional Italian mill. Common in SEA restaurant supply.',
    bagImage: '', logo: null,
  },

  // ── French ───────────────────────────────────
  {
    id: 'gmp_t45_gruau',
    brand: 'Grands Moulins de Paris', name: 'T45 Gruau Rouge',
    type: '00', country: 'fr',
    w: 300, wPublished: false, protein: 12.9, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Strong French T45. For croissants, brioches, long-ferment pizza.',
    bagImage: '', logo: null,
  },
  {
    id: 'gmp_t45_violette',
    brand: 'Grands Moulins de Paris', name: 'T45 Violette',
    type: '00', country: 'fr',
    w: 180, wPublished: false, protein: 9.5, hydration: [55, 61],
    bestFor: [], crowdFavourite: [],
    note: 'Weak T45. For pastries, cakes, short-rise doughs.',
    bagImage: '', logo: null,
  },
  {
    id: 'gmp_t55',
    brand: 'Grands Moulins de Paris', name: 'T55 La Finoise',
    type: 'all_purpose', country: 'fr',
    w: 200, wPublished: false, protein: 10.5, hydration: [57, 63],
    bestFor: [], crowdFavourite: [],
    note: 'Standard French T55. All-purpose. Baguettes, boules, brioche.',
    bagImage: '', logo: null,
  },
  {
    id: 'gmp_t65',
    brand: 'Grands Moulins de Paris', name: 'T65 Tradition',
    type: 'bread', country: 'fr',
    w: 220, wPublished: false, protein: 11.0, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'French bread flour. For baguettes de tradition.',
    bagImage: '', logo: null,
  },
  {
    id: 'francine_t45',
    brand: 'Francine', name: 'Farine T45',
    type: '00', country: 'fr',
    w: 170, wPublished: false, protein: 9.5, hydration: [55, 61],
    bestFor: [], crowdFavourite: [],
    note: 'Consumer supermarket T45. Widely available in France.',
    bagImage: '', logo: null,
  },
  {
    id: 'francine_t55',
    brand: 'Francine', name: 'Farine T55',
    type: 'all_purpose', country: 'fr',
    w: 180, wPublished: false, protein: 10.0, hydration: [57, 63],
    bestFor: [], crowdFavourite: [],
    note: 'Most common French supermarket flour. Standard all-purpose.',
    bagImage: '', logo: null,
  },
  {
    id: 'francine_t65',
    brand: 'Francine', name: 'Farine T65',
    type: 'bread', country: 'fr',
    w: 200, wPublished: false, protein: 10.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'French bread flour. Common in French supermarkets.',
    bagImage: '', logo: null,
  },
  {
    id: 'foricher_t45',
    brand: 'Foricher', name: 'Gruau T45 Bagatelle',
    type: '00', country: 'fr',
    w: 300, wPublished: false, protein: 13.0, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Label Rouge. CRC certified. For viennoiserie and pizza.',
    bagImage: '', logo: null,
  },
  {
    id: 'foricher_t65',
    brand: 'Foricher', name: 'T65 Tradition Bagatelle',
    type: 'bread', country: 'fr',
    w: 220, wPublished: false, protein: 11.0, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'Artisan T65. Label Rouge. For baguettes de tradition.',
    bagImage: '', logo: null,
  },
  {
    id: 'viron_retrodor',
    brand: 'Minoteries Viron', name: 'Rétrodor T65',
    type: 'bread', country: 'fr',
    w: 230, wPublished: false, protein: 11.5, hydration: [63, 69],
    bestFor: [], crowdFavourite: [],
    note: 'Premium French baker\'s flour. Used by top Parisian boulangeries.',
    bagImage: '', logo: null,
  },
  {
    id: 'colagne_t65',
    brand: 'Moulin de Colagne', name: 'T65 Tradition',
    type: 'bread', country: 'fr',
    w: 220, wPublished: false, protein: 11.0, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'Regional French mill. Good artisan bread flour.',
    bagImage: '', logo: null,
  },
  {
    id: 'moulins_bourgeois',
    brand: 'Moulins Bourgeois', name: 'Farine de Tradition',
    type: 'bread', country: 'fr',
    w: 240, wPublished: false, protein: 11.5, hydration: [63, 69],
    bestFor: [], crowdFavourite: [],
    note: 'Premium French traditional flour. Artisan bakers.',
    bagImage: '', logo: null,
  },
  {
    id: 'carrefour_t45',
    brand: 'Carrefour', name: 'Farine de blé T45',
    type: '00', country: 'fr',
    w: 160, wPublished: false, protein: 9.0, hydration: [55, 61],
    bestFor: [], crowdFavourite: [],
    note: 'French supermarket own brand T45. Weak flour.',
    bagImage: '', logo: null,
  },
  {
    id: 'carrefour_t55',
    brand: 'Carrefour', name: 'Farine de blé T55',
    type: 'all_purpose', country: 'fr',
    w: 175, wPublished: false, protein: 10.0, hydration: [57, 63],
    bestFor: [], crowdFavourite: [],
    note: 'Standard French supermarket T55.',
    bagImage: '', logo: null,
  },
  {
    id: 'carrefour_pizza',
    brand: 'Carrefour', name: 'Farine spéciale pizza',
    type: '00', country: 'fr',
    w: 220, wPublished: false, protein: 11.0, hydration: [58, 64],
    bestFor: [], crowdFavourite: [],
    note: 'French supermarket pizza-specific flour.',
    bagImage: '', logo: null,
  },
  {
    id: 'leclerc_t55',
    brand: 'Marque Repère', name: 'Farine T55',
    type: 'all_purpose', country: 'fr',
    w: 170, wPublished: false, protein: 9.5, hydration: [56, 62],
    bestFor: [], crowdFavourite: [],
    note: 'E.Leclerc own brand flour.',
    bagImage: '', logo: null,
  },

  // ── UK ───────────────────────────────────────
  {
    id: 'shipton_t55',
    brand: 'Shipton Mill', name: 'T55 French Flour',
    type: 'all_purpose', country: 'uk',
    w: 200, wPublished: false, protein: 10.5, hydration: [59, 65],
    bestFor: [], crowdFavourite: [],
    note: 'French-style T55 milled or imported by UK\'s Shipton Mill.',
    bagImage: '', logo: null,
  },
  {
    id: 'shipton_strong',
    brand: 'Shipton Mill', name: 'Strong White Bread Flour',
    type: 'bread', country: 'uk',
    w: 250, wPublished: false, protein: 13.0, hydration: [61, 67],
    bestFor: [], crowdFavourite: [],
    note: 'Premium UK bread flour.',
    bagImage: '', logo: null,
  },
  {
    id: 'shipton_t45',
    brand: 'Shipton Mill', name: 'T45 Gruau',
    type: '00', country: 'uk',
    w: 290, wPublished: false, protein: 12.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Strong T45 for croissants and long-ferment pizza.',
    bagImage: '', logo: null,
  },
  {
    id: 'marriages_strong',
    brand: 'Marriages', name: 'Strong White Bread Flour',
    type: 'bread', country: 'uk',
    w: 250, wPublished: true, protein: 13.4, hydration: [61, 67],
    bestFor: [], crowdFavourite: [],
    note: 'UK artisan mill. Good reputation with sourdough bakers.',
    bagImage: '', logo: null,
  },
  {
    id: 'doves_organic_strong',
    brand: 'Doves Farm', name: 'Organic Strong White Bread Flour',
    type: 'bread', country: 'uk',
    w: 240, wPublished: false, protein: 13.0, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Organic UK flour. Common in UK supermarkets.',
    bagImage: '', logo: null,
  },
  {
    id: 'allinson_bread',
    brand: 'Allinson', name: 'Bread Flour Strong White',
    type: 'bread', country: 'uk',
    w: 230, wPublished: false, protein: 12.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'UK supermarket bread flour. Widely available.',
    bagImage: '', logo: null,
  },
  {
    id: 'mcdougalls_bread',
    brand: 'McDougalls', name: 'Strong White Bread Flour',
    type: 'bread', country: 'uk',
    w: 230, wPublished: false, protein: 12.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'UK supermarket bread flour.',
    bagImage: '', logo: null,
  },
  {
    id: 'waitrose_bread',
    brand: 'Waitrose', name: 'Strong White Bread Flour',
    type: 'bread', country: 'uk',
    w: 230, wPublished: false, protein: 12.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'UK supermarket own brand bread flour.',
    bagImage: '', logo: null,
  },
  {
    id: 'marriages_organic_strong',
    brand: 'Marriages', name: 'Organic Strong White Bread Flour',
    type: 'bread', country: 'uk',
    w: 350, wPublished: true, protein: 13.5, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'Organic certified UK artisan mill. Very strong — ideal for sourdough and long ferments.',
    bagImage: '', logo: null,
  },
  {
    id: 'wessex_strong',
    brand: 'Wessex Mill', name: 'Strong White Flour',
    type: 'bread', country: 'uk',
    w: 250, wPublished: false, protein: 12.6, hydration: [61, 67],
    bestFor: [], crowdFavourite: [],
    note: 'UK artisan mill. Good all-round strong white for bread and pizza.',
    bagImage: '', logo: null,
  },
  {
    id: 'matthews_strong_white',
    brand: 'Matthews Cotswold Flour', name: 'Strong White Bakers Flour',
    type: 'bread', country: 'uk',
    w: 240, wPublished: false, protein: 12.5, hydration: [61, 67],
    bestFor: [], crowdFavourite: [],
    note: 'Heritage UK mill. Stone-ground option available. Popular with home sourdough bakers.',
    bagImage: '', logo: null,
  },

  // ── US ───────────────────────────────────────
  {
    id: 'ka_ap',
    brand: 'King Arthur', name: 'All-Purpose Flour',
    type: 'all_purpose', country: 'us',
    w: 200, wPublished: true, protein: 11.7, hydration: [59, 65],
    bestFor: [], crowdFavourite: [],
    note: 'Highest protein US all-purpose. Good for pizza and bread.',
    bagImage: '', logo: null,
  },
  {
    id: 'ka_bread',
    brand: 'King Arthur', name: 'Bread Flour',
    type: 'bread', country: 'us',
    w: 260, wPublished: true, protein: 12.7, hydration: [61, 67],
    bestFor: [], crowdFavourite: ['newyork'],
    note: 'Best US supermarket bread flour. Consistent protein.',
    bagImage: '', logo: null,
  },
  {
    id: 'ka_00',
    brand: 'King Arthur', name: '00 Pizza Flour',
    type: '00', country: 'us',
    w: 200, wPublished: false, protein: 11.5, hydration: [58, 64],
    bestFor: [], crowdFavourite: [],
    note: 'US-milled 00. Blend of soft and hard wheat. Weaker than Italian 00.',
    bagImage: '', logo: null,
  },
  {
    id: 'ka_sir_galahad',
    brand: 'King Arthur', name: 'Sir Galahad',
    type: 'all_purpose', country: 'us',
    w: 200, wPublished: false, protein: 11.7, hydration: [59, 65],
    bestFor: [], crowdFavourite: [],
    note: 'Professional/foodservice version of KA AP. 100% hard red winter wheat.',
    bagImage: '', logo: null,
  },
  {
    id: 'ka_sir_lancelot',
    brand: 'King Arthur', name: 'Sir Lancelot',
    type: '00', country: 'us',
    w: 310, wPublished: false, protein: 14.2, hydration: [64, 70],
    bestFor: [], crowdFavourite: [],
    note: 'High gluten professional flour. For bagels, NY pizza.',
    bagImage: '', logo: null,
  },
  {
    id: 'ka_organic_ap',
    brand: 'King Arthur', name: 'Organic All Purpose',
    type: 'all_purpose', country: 'us',
    w: 195, wPublished: false, protein: 11.0, hydration: [58, 64],
    bestFor: [], crowdFavourite: [],
    note: 'Organic version of KA AP.',
    bagImage: '', logo: null,
  },
  {
    id: 'gold_medal_ap',
    brand: 'Gold Medal', name: 'All-Purpose Flour',
    type: 'all_purpose', country: 'us',
    w: 170, wPublished: false, protein: 10.5, hydration: [57, 63],
    bestFor: [], crowdFavourite: [],
    note: 'Most common US supermarket flour. Lower protein than KA.',
    bagImage: '', logo: null,
  },
  {
    id: 'gold_medal_bread',
    brand: 'Gold Medal', name: 'Bread Flour',
    type: 'bread', country: 'us',
    w: 240, wPublished: false, protein: 12.3, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Standard US bread flour.',
    bagImage: '', logo: null,
  },
  {
    id: 'gold_medal_harvest',
    brand: 'Gold Medal', name: 'Harvest King / Better for Bread',
    type: 'bread', country: 'us',
    w: 240, wPublished: false, protein: 12.0, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Hard winter wheat. Popular with home bread bakers.',
    bagImage: '', logo: null,
  },
  {
    id: 'gold_medal_full_strength',
    brand: 'Gold Medal', name: 'Full Strength',
    type: '00', country: 'us',
    w: 270, wPublished: false, protein: 12.6, hydration: [61, 67],
    bestFor: [], crowdFavourite: [],
    note: 'Spring wheat. Professional grade. For bagels and pizza.',
    bagImage: '', logo: null,
  },
  {
    id: 'bobs_artisan_bread',
    brand: "Bob's Red Mill", name: 'Artisan Bread Flour',
    type: 'bread', country: 'us',
    w: 250, wPublished: true, protein: 13.0, hydration: [61, 67],
    bestFor: [], crowdFavourite: [],
    note: 'With malted barley. Popular US artisan bread flour.',
    bagImage: '', logo: null,
  },
  {
    id: 'bobs_ap',
    brand: "Bob's Red Mill", name: 'All-Purpose Flour',
    type: 'all_purpose', country: 'us',
    w: 185, wPublished: false, protein: 11.0, hydration: [58, 64],
    bestFor: [], crowdFavourite: [],
    note: 'Unbleached. Common in US natural food stores.',
    bagImage: '', logo: null,
  },
  {
    id: 'pillsbury_ap',
    brand: 'Pillsbury', name: 'All-Purpose Flour',
    type: 'all_purpose', country: 'us',
    w: 165, wPublished: false, protein: 10.5, hydration: [57, 63],
    bestFor: [], crowdFavourite: [],
    note: 'Standard US supermarket flour.',
    bagImage: '', logo: null,
  },
  {
    id: 'pillsbury_bread',
    brand: 'Pillsbury', name: 'Bread Flour',
    type: 'bread', country: 'us',
    w: 230, wPublished: false, protein: 12.0, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Standard US bread flour.',
    bagImage: '', logo: null,
  },
  {
    id: 'central_high_mountain',
    brand: 'Central Milling', name: 'High Mountain',
    type: 'bread', country: 'us',
    w: 270, wPublished: false, protein: 13.5, hydration: [63, 69],
    bestFor: [], crowdFavourite: [],
    note: 'Premium US artisan flour. Favored by sourdough bakers.',
    bagImage: '', logo: null,
  },
  {
    id: 'central_00',
    brand: 'Central Milling', name: 'Type 00 Normal',
    type: '00', country: 'us',
    w: 240, wPublished: false, protein: 11.5, hydration: [59, 65],
    bestFor: [], crowdFavourite: [],
    note: 'US-milled 00. More accessible than imported.',
    bagImage: '', logo: null,
  },
  {
    id: 'central_type85',
    brand: 'Central Milling', name: 'Organic Type 85',
    type: 'bread', country: 'us',
    w: 240, wPublished: false, protein: 12.5, hydration: [67, 73],
    bestFor: [], crowdFavourite: [],
    note: 'High extraction. Excellent for sourdough and rustic loaves.',
    bagImage: '', logo: null,
  },
  {
    id: 'giustos_bread',
    brand: "Giusto's", name: 'Bread Flour',
    type: 'bread', country: 'us',
    w: 250, wPublished: false, protein: 12.5, hydration: [61, 67],
    bestFor: [], crowdFavourite: [],
    note: 'Premium California mill. Good for artisan bread.',
    bagImage: '', logo: null,
  },
  {
    id: 'giustos_high_perf',
    brand: "Giusto's", name: 'High Performance Bread Flour',
    type: '00', country: 'us',
    w: 290, wPublished: false, protein: 14.5, hydration: [64, 70],
    bestFor: [], crowdFavourite: [],
    note: 'Very high protein. For NY-style and long ferment applications.',
    bagImage: '', logo: null,
  },
  {
    id: 'white_lily_ap',
    brand: 'White Lily', name: 'All Purpose Flour',
    type: 'all_purpose', country: 'us',
    w: 120, wPublished: false, protein: 8.0, hydration: [53, 59],
    bestFor: [], crowdFavourite: [],
    note: 'Very soft Southern wheat. Not suitable for pizza/bread.',
    bagImage: '', logo: null,
  },
  {
    id: 'white_lily_bread',
    brand: 'White Lily', name: 'Bread Flour',
    type: 'bread', country: 'us',
    w: 230, wPublished: false, protein: 11.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Finely ground. Similar protein to KA AP. Lighter texture.',
    bagImage: '', logo: null,
  },
  {
    id: 'hodgson_bread',
    brand: 'Hodgson Mill', name: 'Best for Bread',
    type: 'bread', country: 'us',
    w: 230, wPublished: false, protein: 12.0, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'US bread flour.',
    bagImage: '', logo: null,
  },

  // ── Canada ───────────────────────────────────
  {
    id: 'robin_hood_ap',
    brand: 'Robin Hood', name: 'All Purpose Flour',
    type: 'all_purpose', country: 'ca',
    w: 230, wPublished: false, protein: 13.3, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Canadian wheat. Higher protein than US AP flour.',
    bagImage: '', logo: null,
  },
  {
    id: 'robin_hood_bread',
    brand: 'Robin Hood', name: 'Best for Bread',
    type: 'bread', country: 'ca',
    w: 260, wPublished: false, protein: 13.3, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'Canadian bread flour. High protein Canadian wheat.',
    bagImage: '', logo: null,
  },
  {
    id: 'five_roses_ap',
    brand: 'Five Roses', name: 'All Purpose Flour',
    type: 'all_purpose', country: 'ca',
    w: 230, wPublished: false, protein: 13.3, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Canadian flour. High protein like Robin Hood.',
    bagImage: '', logo: null,
  },
  {
    id: 'anitas_ap',
    brand: "Anita's", name: 'Organic All Purpose Flour',
    type: 'all_purpose', country: 'ca',
    w: 220, wPublished: false, protein: 12.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Premium Canadian organic flour.',
    bagImage: '', logo: null,
  },

  // ── Australia ────────────────────────────────
  {
    id: 'wholegrain_milling',
    brand: 'Wholegrain Milling', name: 'Premium Bakers White High Protein',
    type: 'bread', country: 'au',
    w: 260, wPublished: false, protein: 13.5, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'Australian organic. Available in Singapore via specialty stores.',
    bagImage: '', logo: null,
  },
  {
    id: 'coles_plain',
    brand: 'Coles', name: 'Plain Flour',
    type: 'all_purpose', country: 'au',
    w: 175, wPublished: false, protein: 10.0, hydration: [57, 63],
    bestFor: [], crowdFavourite: [],
    note: 'Australian supermarket own brand.',
    bagImage: '', logo: null,
  },
  {
    id: 'woolworths_bread',
    brand: 'Woolworths', name: 'Bread and Pizza Flour',
    type: 'bread', country: 'au',
    w: 240, wPublished: false, protein: 12.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Australian supermarket bread flour.',
    bagImage: '', logo: null,
  },
  {
    id: 'defiance_bread',
    brand: 'Defiance', name: 'Bakers Flour',
    type: 'bread', country: 'au',
    w: 250, wPublished: false, protein: 13.0, hydration: [61, 67],
    bestFor: [], crowdFavourite: [],
    note: 'Australian commercial bakers flour.',
    bagImage: '', logo: null,
  },

  // ── Singapore ────────────────────────────────
  {
    id: 'prima_bread',
    brand: 'Prima', name: 'Bread Flour',
    type: 'bread', country: 'sg',
    w: 240, wPublished: false, protein: 12.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Leading Singapore flour brand. Available at FairPrice and most supermarkets.',
    bagImage: '', logo: null,
  },
  {
    id: 'prima_plain',
    brand: 'Prima', name: 'Plain Flour',
    type: 'all_purpose', country: 'sg',
    w: 170, wPublished: false, protein: 9.5, hydration: [57, 63],
    bestFor: [], crowdFavourite: [],
    note: 'Standard Singapore all-purpose flour.',
    bagImage: '', logo: null,
  },
  {
    id: 'prima_superior',
    brand: 'Prima', name: 'Superior Bread Flour',
    type: 'bread', country: 'sg',
    w: 260, wPublished: false, protein: 13.5, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'High protein. For Japanese-style milk bread and buns.',
    bagImage: '', logo: null,
  },
  {
    id: 'prima_clover',
    brand: 'Prima', name: 'Clover Bread Flour',
    type: 'bread', country: 'sg',
    w: 250, wPublished: false, protein: 12.8, hydration: [61, 67],
    bestFor: [], crowdFavourite: [],
    note: '12.8% protein. Common in Singapore commercial bakeries.',
    bagImage: '', logo: null,
  },
  {
    id: 'prima_artisan',
    brand: 'Prima', name: 'Artisan Bread Flour',
    type: 'bread', country: 'sg',
    w: 260, wPublished: false, protein: 13.0, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'For ciabatta and artisan loaves. Available in Singapore.',
    bagImage: '', logo: null,
  },
  {
    id: 'bake_king_bread',
    brand: 'Bake King', name: 'Bread Flour',
    type: 'bread', country: 'sg',
    w: 240, wPublished: false, protein: 12.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Singapore brand. Available at Phoon Huat and baking stores.',
    bagImage: '', logo: null,
  },
  {
    id: 'bake_king_plain',
    brand: 'Bake King', name: 'Plain Flour',
    type: 'all_purpose', country: 'sg',
    w: 165, wPublished: false, protein: 9.5, hydration: [57, 63],
    bestFor: [], crowdFavourite: [],
    note: 'Common Singapore household flour.',
    bagImage: '', logo: null,
  },
  {
    id: 'phoon_huat_bread',
    brand: 'Phoon Huat', name: 'Super Baker Bread Flour',
    type: 'bread', country: 'sg',
    w: 250, wPublished: false, protein: 13.0, hydration: [61, 67],
    bestFor: [], crowdFavourite: [],
    note: 'Available at Phoon Huat baking supply stores in Singapore.',
    bagImage: '', logo: null,
  },
  {
    id: 'sun_hong_bread',
    brand: 'Sun Hong', name: 'High Protein Bread Flour',
    type: 'bread', country: 'sg',
    w: 240, wPublished: false, protein: 12.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Singapore commercial bakery brand.',
    bagImage: '', logo: null,
  },

  // ── Malaysia ─────────────────────────────────
  {
    id: 'bagus_bread',
    brand: 'Bagus', name: 'Bread Flour',
    type: 'bread', country: 'my',
    w: 240, wPublished: false, protein: 12.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Malaysian brand. Available in Singapore and Malaysia.',
    bagImage: '', logo: null,
  },
  {
    id: 'payless_bread',
    brand: 'Payless', name: 'Bread Flour',
    type: 'bread', country: 'my',
    w: 235, wPublished: false, protein: 12.0, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Malaysian supermarket bread flour.',
    bagImage: '', logo: null,
  },
  {
    id: 'renown_bread',
    brand: 'Renown', name: 'Bread Flour',
    type: 'bread', country: 'my',
    w: 240, wPublished: false, protein: 12.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Malaysian bread flour. Common in SEA.',
    bagImage: '', logo: null,
  },

  // ── Japan ────────────────────────────────────
  {
    id: 'nisshin_camellia',
    brand: 'Nisshin', name: 'Bread Flour',
    type: 'bread', country: 'jp',
    w: 260, wPublished: true, protein: 13.5, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'Japanese premium bread flour. Popular in SEA Asian bakeries.',
    bagImage: '', logo: null,
  },
  {
    id: 'nisshin_violet',
    brand: 'Nisshin', name: 'Violet All Purpose',
    type: 'all_purpose', country: 'jp',
    w: 180, wPublished: false, protein: 10.0, hydration: [57, 63],
    bestFor: [], crowdFavourite: [],
    note: 'Japanese AP flour. Widely available in Asian supermarkets.',
    bagImage: '', logo: null,
  },
  {
    id: 'showa_camellia',
    brand: 'Showa', name: 'Camellia Bread Flour',
    type: 'bread', country: 'jp',
    w: 260, wPublished: false, protein: 13.5, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'Top Japanese bread flour. Used in many SEA bakeries.',
    bagImage: '', logo: null,
  },
  {
    id: 'showa_lys_dor',
    brand: 'Showa', name: "Lys d'Or",
    type: '00', country: 'jp',
    w: 300, wPublished: false, protein: 14.5, hydration: [64, 70],
    bestFor: [], crowdFavourite: [],
    note: 'Very high gluten Japanese flour. For chewy NY-style pizza.',
    bagImage: '', logo: null,
  },

  // ── Generic ──────────────────────────────────
  {
    id: 'generic_00',
    brand: 'Generic', name: 'Pizza 00 Flour',
    type: '00', country: 'it',
    w: 250, wPublished: false, protein: 12.0, hydration: [59, 65],
    bestFor: [], crowdFavourite: [],
    note: 'Generic Italian 00 pizza flour estimate.',
    bagImage: '', logo: null,
  },
  {
    id: 'generic_strong00',
    brand: 'Generic', name: 'Strong 00 / High Protein 00',
    type: '00', country: 'it',
    w: 300, wPublished: false, protein: 13.5, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'Generic strong 00 estimate.',
    bagImage: '', logo: null,
  },
  {
    id: 'generic_bread',
    brand: 'Generic', name: 'Bread Flour / T65',
    type: 'bread', country: 'us',
    w: 230, wPublished: false, protein: 12.5, hydration: [61, 67],
    bestFor: [], crowdFavourite: [],
    note: 'Generic bread flour estimate.',
    bagImage: '', logo: null,
  },
  {
    id: 'generic_ap',
    brand: 'Generic', name: 'All Purpose / T55',
    type: 'all_purpose', country: 'us',
    w: 160, wPublished: false, protein: 10.5, hydration: [57, 63],
    bestFor: [], crowdFavourite: [],
    note: 'Generic all-purpose estimate.',
    bagImage: '', logo: null,
  },
  {
    id: 'generic_manitoba',
    brand: 'Generic', name: 'Manitoba Flour',
    type: 'high_gluten', country: 'it',
    w: 380, wPublished: false, protein: 14.5, hydration: [65, 71],
    bestFor: [], crowdFavourite: [],
    note: 'Generic Manitoba estimate. Very strong blending flour.',
    bagImage: '', logo: null,
  },
  {
    id: 'generic_semolina',
    brand: 'Generic', name: 'Semolina / Semola',
    type: 'semolina', country: 'it',
    w: 200, wPublished: false, protein: 13.0, hydration: [59, 65],
    bestFor: [], crowdFavourite: [],
    note: 'Generic semolina estimate.',
    bagImage: '', logo: null,
  },
  {
    id: 'generic_wholemeal',
    brand: 'Generic', name: 'Whole Wheat / Wholemeal',
    type: 'wholemeal', country: 'us',
    w: 220, wPublished: false, protein: 13.0, hydration: [65, 71],
    bestFor: [], crowdFavourite: [],
    note: 'Generic whole wheat estimate.',
    bagImage: '', logo: null,
  },
  {
    id: 'generic_rye',
    brand: 'Generic', name: 'Rye Flour / Seigle',
    type: 'rye', country: 'de',
    w: 150, wPublished: false, protein: 8.0, hydration: [72, 78],
    bestFor: [], crowdFavourite: [],
    note: 'Generic rye flour estimate. High enzyme activity.',
    bagImage: '', logo: null,
  },

  // ── More Italian ─────────────────────────────
  {
    id: 'pivetti_granmaestro',
    brand: 'Molino Pivetti', name: 'Gran Maestro',
    type: '00', country: 'it',
    w: 330, wPublished: true, protein: 13.5, hydration: [63, 69],
    bestFor: [], crowdFavourite: [],
    note: 'Professional 00 for very long cold ferments. High stability.',
    bagImage: '', logo: null,
  },
  {
    id: 'pivetti_ideale',
    brand: 'Molino Pivetti', name: 'Ideale',
    type: '00', country: 'it',
    w: 280, wPublished: true, protein: 12.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Versatile professional 00. 24-48h ferments.',
    bagImage: '', logo: null,
  },
  {
    id: 'dalla_giovanna_uniqua_blu',
    brand: 'Molino Dallagiovanna', name: 'Uniqua Blu',
    type: 'bread', country: 'it',
    w: 280, wPublished: true, protein: 13.0, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'Versatile type 1 blend. For pizza, bread and focaccia.',
    bagImage: '', logo: null,
  },
  {
    id: 'dalla_giovanna_uniqua_gialla',
    brand: 'Molino Dallagiovanna', name: 'Uniqua Gialla',
    type: '00', country: 'it',
    w: 330, wPublished: true, protein: 14.0, hydration: [64, 70],
    bestFor: [], crowdFavourite: [],
    note: 'Strong 00 blend for biga/poolish and long ferments.',
    bagImage: '', logo: null,
  },
  {
    id: 'pasini_vivace',
    brand: 'Molino Pasini', name: 'Vivace',
    type: '00', country: 'it',
    w: 270, wPublished: true, protein: 12.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Neapolitan-style 00. AVPN approved. Excellent extensibility.',
    bagImage: '', logo: null,
  },
  {
    id: 'pasini_forte',
    brand: 'Molino Pasini', name: 'Forte',
    type: '00', country: 'it',
    w: 320, wPublished: true, protein: 13.5, hydration: [63, 69],
    bestFor: [], crowdFavourite: [],
    note: 'Strong 00 for long cold ferments and biga.',
    bagImage: '', logo: null,
  },
  {
    id: 'italmill_blu',
    brand: 'Italmill', name: 'Blu',
    type: '00', country: 'it',
    w: 260, wPublished: true, protein: 12.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Classic Neapolitan 00. AVPN approved. Good balance of strength and extensibility.',
    bagImage: '', logo: null,
  },
  {
    id: 'italmill_oro',
    brand: 'Italmill', name: 'Oro',
    type: '00', country: 'it',
    w: 310, wPublished: true, protein: 13.5, hydration: [63, 69],
    bestFor: [], crowdFavourite: [],
    note: 'Premium 00 for 48-72h cold ferment pizza.',
    bagImage: '', logo: null,
  },
  {
    id: 'quaglia_universale',
    brand: 'Molino Quaglia', name: 'Petra 1',
    type: '1', country: 'it',
    w: 260, wPublished: false, protein: 12.5, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'Stone ground Tipo 1. High bran content. For modern Neapolitan and sourdough.',
    bagImage: '', logo: null,
  },
  {
    id: 'rossetto_00',
    brand: 'Mulino Rossetto', name: 'Farina 00 Pizza',
    type: '00', country: 'it',
    w: 250, wPublished: false, protein: 12.0, hydration: [59, 65],
    bestFor: [], crowdFavourite: [],
    note: 'Italian retail pizza 00. Available in Italian supermarkets.',
    bagImage: '', logo: null,
  },
  {
    id: 'molino_agostini_00',
    brand: 'Molino Agostini', name: 'Farina 00 Tipo Pizza',
    type: '00', country: 'it',
    w: 270, wPublished: false, protein: 12.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Regional Italian mill. Good pizza 00.',
    bagImage: '', logo: null,
  },
  {
    id: 'lo_conte_forte',
    brand: 'Lo Conte', name: 'Farina Forte',
    type: '00', country: 'it',
    w: 300, wPublished: false, protein: 13.0, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'Strong 00 for medium to long ferments.',
    bagImage: '', logo: null,
  },
  {
    id: 'caputo_bio',
    brand: 'Caputo', name: 'Bio Organica',
    type: '00', country: 'it',
    w: 250, wPublished: true, protein: 12.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'USDA Organic certified 00. Same profile as Pizzeria.',
    bagImage: '', logo: null,
  },
  {
    id: 'polselli_forte',
    brand: 'Polselli', name: 'Forte W360',
    type: 'high_gluten', country: 'it',
    w: 360, wPublished: true, protein: 14.5, hydration: [65, 71],
    bestFor: [], crowdFavourite: [],
    note: 'Powerful blending flour. For extreme long ferments.',
    bagImage: '', logo: null,
  },
  {
    id: 'divella_00',
    brand: 'Divella', name: 'Farina 00',
    type: '00', country: 'it',
    w: 200, wPublished: false, protein: 11.0, hydration: [57, 63],
    bestFor: [], crowdFavourite: [],
    note: 'Italian mass-market 00. Common in Italian supermarkets.',
    bagImage: '', logo: null,
  },
  {
    id: 'barilla_semolina',
    brand: 'Barilla', name: 'Semola Rimacinata',
    type: 'semolina', country: 'it',
    w: 190, wPublished: false, protein: 13.0, hydration: [58, 64],
    bestFor: [], crowdFavourite: [],
    note: 'Italian supermarket semolina. For pasta and Roman pizza.',
    bagImage: '', logo: null,
  },
  {
    id: 'casillo_semola',
    brand: 'Molino Casillo', name: 'Semola di Grano Duro',
    type: 'semolina', country: 'it',
    w: 200, wPublished: false, protein: 13.5, hydration: [59, 65],
    bestFor: [], crowdFavourite: [],
    note: 'Professional durum wheat semolina. For pasta and Pugliese bread.',
    bagImage: '', logo: null,
  },
  {
    id: 'mulino_marino_integrale',
    brand: 'Mulino Marino', name: 'Farina Integrale',
    type: 'wholemeal', country: 'it',
    w: 220, wPublished: false, protein: 13.0, hydration: [65, 71],
    bestFor: [], crowdFavourite: [],
    note: 'Organic stone ground wholemeal. Rich bran. For rustic sourdough.',
    bagImage: '', logo: null,
  },
  {
    id: 'molino_grassi_type1',
    brand: 'Molino Grassi', name: 'Tipo 1 Organic',
    type: '1', country: 'it',
    w: 250, wPublished: false, protein: 12.5, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'Organic tipo 1 with germ. Good for modern sourdough pizza.',
    bagImage: '', logo: null,
  },
  {
    id: 'petra_1',
    brand: 'Petra', name: '1',
    type: '1', country: 'it',
    w: 270, wPublished: false, protein: 12.5, hydration: [64, 70],
    bestFor: [], crowdFavourite: [],
    note: 'Type 1 semi-wholemeal. Stone ground. Full flavour.',
    bagImage: '', logo: null,
  },
  {
    id: 'dalla_giovanna_segreta',
    brand: 'Molino Dallagiovanna', name: 'La Segreta',
    type: '00', country: 'it',
    w: 390, wPublished: true, protein: 15.0, hydration: [66, 72],
    bestFor: [], crowdFavourite: [],
    note: 'Very high gluten professional flour for extreme fermentations.',
    bagImage: '', logo: null,
  },
  {
    id: 'agugiaro_super',
    brand: 'Agugiaro & Figna', name: 'Super Blue Label',
    type: '00', country: 'it',
    w: 280, wPublished: true, protein: 13.0, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'Standard professional 00. Wide distribution in Italy.',
    bagImage: '', logo: null,
  },
  {
    id: 'agugiaro_verde',
    brand: 'Agugiaro & Figna', name: 'Verde',
    type: '00', country: 'it',
    w: 360, wPublished: true, protein: 14.5, hydration: [65, 71],
    bestFor: [], crowdFavourite: [],
    note: 'Very strong professional 00 for 72h+ cold ferments.',
    bagImage: '', logo: null,
  },
  {
    id: 'grano_armando_00',
    brand: 'Grano Armando', name: 'Farina 00',
    type: '00', country: 'it',
    w: 240, wPublished: false, protein: 12.0, hydration: [59, 65],
    bestFor: [], crowdFavourite: [],
    note: '100% Italian wheat certified supply chain. Consumer brand.',
    bagImage: '', logo: null,
  },

  // ── More French ──────────────────────────────
  {
    id: 'soufflet_t45',
    brand: 'Moulins Soufflet', name: 'T45 Gruau',
    type: 'T45', country: 'fr',
    w: 300, wPublished: false, protein: 13.0, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Strong T45 from major French mill. For viennoiserie and pizza.',
    bagImage: '', logo: null,
  },
  {
    id: 'soufflet_t65',
    brand: 'Moulins Soufflet', name: 'T65 Tradition',
    type: 'bread', country: 'fr',
    w: 220, wPublished: false, protein: 11.0, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'Classic French tradition baguette flour.',
    bagImage: '', logo: null,
  },
  {
    id: 'storione_t45',
    brand: 'Moulins Storione', name: 'T45 Gruau Or',
    type: 'T45', country: 'fr',
    w: 310, wPublished: false, protein: 13.5, hydration: [61, 67],
    bestFor: [], crowdFavourite: [],
    note: 'Premium French gruau. Excellent for croissants and long-ferment pizza.',
    bagImage: '', logo: null,
  },
  {
    id: 'minoterie_brie_t65',
    brand: 'Minoterie de la Brie', name: 'T65 Tradition',
    type: 'bread', country: 'fr',
    w: 230, wPublished: false, protein: 11.5, hydration: [63, 69],
    bestFor: [], crowdFavourite: [],
    note: 'French regional mill near Paris. Artisan boulangeries.',
    bagImage: '', logo: null,
  },
  {
    id: 'decollogne_t55',
    brand: 'Moulin Decollogne', name: 'T55 Classique',
    type: 'T55', country: 'fr',
    w: 180, wPublished: false, protein: 10.0, hydration: [57, 63],
    bestFor: [], crowdFavourite: [],
    note: 'Standard French household T55.',
    bagImage: '', logo: null,
  },
  {
    id: 'celnat_t65_bio',
    brand: 'Celnat', name: 'T65 Bio',
    type: 'bread', country: 'fr',
    w: 210, wPublished: false, protein: 11.0, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'French organic T65. Available in bio stores across France.',
    bagImage: '', logo: null,
  },
  {
    id: 'celnat_t80_bio',
    brand: 'Celnat', name: 'T80 Bio',
    type: 'T80', country: 'fr',
    w: 200, wPublished: false, protein: 11.5, hydration: [64, 70],
    bestFor: [], crowdFavourite: [],
    note: 'Organic semi-whole flour. Nutty flavour, good for country loaves.',
    bagImage: '', logo: null,
  },
  {
    id: 'foricher_t80',
    brand: 'Foricher', name: 'T80 Tradition Bise',
    type: 'T80', country: 'fr',
    w: 210, wPublished: false, protein: 11.5, hydration: [64, 70],
    bestFor: [], crowdFavourite: [],
    note: 'Artisan semi-whole T80. For rustic baguettes and country bread.',
    bagImage: '', logo: null,
  },
  {
    id: 'gmp_t80',
    brand: 'Grands Moulins de Paris', name: 'T80 Bio',
    type: 'T80', country: 'fr',
    w: 200, wPublished: false, protein: 11.5, hydration: [64, 70],
    bestFor: [], crowdFavourite: [],
    note: 'Organic semi-wholemeal from Grands Moulins de Paris.',
    bagImage: '', logo: null,
  },
  {
    id: 'gmp_t110',
    brand: 'Grands Moulins de Paris', name: 'T110 Intégrale',
    type: 'T110', country: 'fr',
    w: 190, wPublished: false, protein: 12.0, hydration: [66, 72],
    bestFor: [], crowdFavourite: [],
    note: 'High extraction French flour. Earthy flavour.',
    bagImage: '', logo: null,
  },
  {
    id: 'francine_t110',
    brand: 'Francine', name: 'Farine T110',
    type: 'T110', country: 'fr',
    w: 185, wPublished: false, protein: 12.0, hydration: [66, 72],
    bestFor: [], crowdFavourite: [],
    note: 'French supermarket high-extraction flour.',
    bagImage: '', logo: null,
  },
  {
    id: 'francine_seigle',
    brand: 'Francine', name: 'Farine de Seigle',
    type: 'rye', country: 'fr',
    w: 150, wPublished: false, protein: 8.5, hydration: [70, 76],
    bestFor: [], crowdFavourite: [],
    note: 'French supermarket rye. For pain de seigle and sourdough levain.',
    bagImage: '', logo: null,
  },
  {
    id: 'auchan_t55',
    brand: 'Auchan', name: 'Farine T55',
    type: 'T55', country: 'fr',
    w: 165, wPublished: false, protein: 9.5, hydration: [56, 62],
    bestFor: [], crowdFavourite: [],
    note: 'French supermarket own brand T55.',
    bagImage: '', logo: null,
  },
  {
    id: 'monoprix_t55',
    brand: 'Monoprix', name: 'Farine T55',
    type: 'T55', country: 'fr',
    w: 165, wPublished: false, protein: 9.5, hydration: [56, 62],
    bestFor: [], crowdFavourite: [],
    note: 'French urban supermarket own brand T55.',
    bagImage: '', logo: null,
  },
  {
    id: 'viron_campaillette',
    brand: 'Minoteries Viron', name: 'Campaillette T65',
    type: 'bread', country: 'fr',
    w: 220, wPublished: false, protein: 11.0, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'Rustic T65 blend. For pain de campagne and sourdough.',
    bagImage: '', logo: null,
  },
  {
    id: 'foricher_gruau_rouge',
    brand: 'Foricher', name: 'Gruau Rouge T45',
    type: 'T45', country: 'fr',
    w: 320, wPublished: false, protein: 13.5, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'Very strong gruau. For croissants, brioches, pizza long ferments.',
    bagImage: '', logo: null,
  },
  {
    id: 'minoterie_chariot_t65',
    brand: 'Minoterie Chariot', name: 'T65 Label Rouge',
    type: 'bread', country: 'fr',
    w: 240, wPublished: false, protein: 11.5, hydration: [63, 69],
    bestFor: [], crowdFavourite: [],
    note: 'Label Rouge T65. Premium artisan boulangerie flour.',
    bagImage: '', logo: null,
  },
  {
    id: 'moulin_portieux_t55',
    brand: 'Moulin de Portieux', name: 'T55 Tradition',
    type: 'T55', country: 'fr',
    w: 190, wPublished: false, protein: 10.5, hydration: [58, 64],
    bestFor: [], crowdFavourite: [],
    note: 'Northeast French mill. Good standard T55.',
    bagImage: '', logo: null,
  },
  {
    id: 'paulette_t65',
    brand: 'Paulette', name: 'T65 Bio Tradition',
    type: 'bread', country: 'fr',
    w: 215, wPublished: false, protein: 11.0, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'GMP sub-brand. Organic T65 for tradition baguettes.',
    bagImage: '', logo: null,
  },
  {
    id: 'bio_planete_t80',
    brand: 'Bio Planète', name: 'Farine T80',
    type: 'T80', country: 'fr',
    w: 205, wPublished: false, protein: 11.5, hydration: [63, 69],
    bestFor: [], crowdFavourite: [],
    note: 'French organic brand. Semi-wholemeal T80.',
    bagImage: '', logo: null,
  },

  // ── More UK ──────────────────────────────────
  {
    id: 'cotswold_strong',
    brand: 'Cotswold Flour', name: 'Very Strong White',
    type: 'bread', country: 'uk',
    w: 280, wPublished: false, protein: 14.0, hydration: [63, 69],
    bestFor: [], crowdFavourite: [],
    note: 'High protein UK white. Popular with sourdough bakers.',
    bagImage: '', logo: null,
  },
  {
    id: 'bacheldre_strong',
    brand: 'Bacheldre Watermill', name: 'Organic Strong White',
    type: 'bread', country: 'uk',
    w: 255, wPublished: false, protein: 13.0, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'Heritage UK mill. Stone ground organic. Excellent sourdough flour.',
    bagImage: '', logo: null,
  },
  {
    id: 'marriages_heritage',
    brand: 'Marriages', name: 'Canadian Strong White',
    type: 'bread', country: 'uk',
    w: 280, wPublished: false, protein: 13.5, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'Marriages milled from Canadian hard wheat. Very high protein.',
    bagImage: '', logo: null,
  },
  {
    id: 'shipton_wholemeal',
    brand: 'Shipton Mill', name: 'Organic Wholemeal',
    type: 'wholemeal', country: 'uk',
    w: 220, wPublished: false, protein: 13.0, hydration: [65, 71],
    bestFor: [], crowdFavourite: [],
    note: 'Stone ground organic. Classic UK wholemeal for sourdough.',
    bagImage: '', logo: null,
  },
  {
    id: 'shipton_rye',
    brand: 'Shipton Mill', name: 'Organic Dark Rye',
    type: 'rye', country: 'uk',
    w: 145, wPublished: false, protein: 8.0, hydration: [70, 76],
    bestFor: [], crowdFavourite: [],
    note: 'UK organic dark rye. For sourdough starters and rye loaves.',
    bagImage: '', logo: null,
  },
  {
    id: 'doves_wholemeal',
    brand: 'Doves Farm', name: 'Organic Wholemeal Flour',
    type: 'wholemeal', country: 'uk',
    w: 215, wPublished: false, protein: 13.0, hydration: [65, 71],
    bestFor: [], crowdFavourite: [],
    note: 'Organic UK wholemeal. Widely available in UK supermarkets.',
    bagImage: '', logo: null,
  },
  {
    id: 'tesco_strong',
    brand: 'Tesco', name: 'Strong White Bread Flour',
    type: 'bread', country: 'uk',
    w: 230, wPublished: false, protein: 12.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'UK supermarket own brand bread flour.',
    bagImage: '', logo: null,
  },
  {
    id: 'sainsburys_strong',
    brand: "Sainsbury's", name: 'Strong White Bread Flour',
    type: 'bread', country: 'uk',
    w: 230, wPublished: false, protein: 12.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'UK supermarket own brand bread flour.',
    bagImage: '', logo: null,
  },
  {
    id: 'asda_strong',
    brand: 'ASDA', name: 'Strong White Bread Flour',
    type: 'bread', country: 'uk',
    w: 225, wPublished: false, protein: 12.0, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'UK supermarket own brand bread flour.',
    bagImage: '', logo: null,
  },
  {
    id: 'marriages_00',
    brand: 'Marriages', name: 'Pizza Flour 00',
    type: '00', country: 'uk',
    w: 260, wPublished: false, protein: 12.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'UK 00 pizza flour from Marriages mill. Accessible for home bakers.',
    bagImage: '', logo: null,
  },
  {
    id: 'redbournbury_strong',
    brand: 'Redbournbury Mill', name: 'Strong White Flour',
    type: 'bread', country: 'uk',
    w: 255, wPublished: false, protein: 13.0, hydration: [61, 67],
    bestFor: [], crowdFavourite: [],
    note: 'Heritage watermill. Stone ground. Artisan home bakers favourite.',
    bagImage: '', logo: null,
  },
  {
    id: 'doves_spelt',
    brand: 'Doves Farm', name: 'Organic Spelt Flour',
    type: 'spelt', country: 'uk',
    w: 200, wPublished: false, protein: 12.0, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Organic spelt. Nutty flavour. Extensible gluten, lower W.',
    bagImage: '', logo: null,
  },
  {
    id: 'marriages_strong_wholemeal',
    brand: 'Marriages', name: 'Wholemeal Strong Flour',
    type: 'wholemeal', country: 'uk',
    w: 235, wPublished: false, protein: 13.0, hydration: [65, 71],
    bestFor: [], crowdFavourite: [],
    note: 'UK wholemeal bread flour. 100% UK wheat.',
    bagImage: '', logo: null,
  },
  {
    id: 'bacheldre_wholemeal',
    brand: 'Bacheldre Watermill', name: 'Organic Wholemeal',
    type: 'wholemeal', country: 'uk',
    w: 210, wPublished: false, protein: 12.5, hydration: [65, 71],
    bestFor: [], crowdFavourite: [],
    note: 'Stone ground heritage mill. Rich bran content.',
    bagImage: '', logo: null,
  },
  {
    id: 'tesco_plain',
    brand: 'Tesco', name: 'Plain White Flour',
    type: 'all_purpose', country: 'uk',
    w: 165, wPublished: false, protein: 10.0, hydration: [56, 62],
    bestFor: [], crowdFavourite: [],
    note: 'Standard UK all-purpose supermarket flour.',
    bagImage: '', logo: null,
  },
  {
    id: 'allinson_strong_wholemeal',
    brand: 'Allinson', name: 'Strong Wholemeal',
    type: 'wholemeal', country: 'uk',
    w: 220, wPublished: false, protein: 12.5, hydration: [65, 71],
    bestFor: [], crowdFavourite: [],
    note: 'UK mainstream wholemeal bread flour.',
    bagImage: '', logo: null,
  },
  {
    id: 'john_letts_heritage',
    brand: 'Gilchesters Organics', name: 'Heritage Stoneground White',
    type: 'bread', country: 'uk',
    w: 230, wPublished: false, protein: 12.5, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'Heritage UK grain blend. Stone ground. Complex flavour.',
    bagImage: '', logo: null,
  },
  {
    id: 'wrens_spelt',
    brand: "Wren's Organics", name: 'Organic Spelt Flour',
    type: 'spelt', country: 'uk',
    w: 195, wPublished: false, protein: 11.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'UK organic spelt. Popular in UK artisan bakeries.',
    bagImage: '', logo: null,
  },

  // ── Germany ──────────────────────────────────
  {
    id: 'rosenmehl_type550',
    brand: 'Rosenmehl', name: 'Type 550',
    type: 'T55', country: 'de',
    w: 210, wPublished: false, protein: 11.0, hydration: [59, 65],
    bestFor: [], crowdFavourite: [],
    note: 'German standard white flour. Equivalent to T55/AP. Widely used.',
    bagImage: '', logo: null,
  },
  {
    id: 'rosenmehl_type812',
    brand: 'Rosenmehl', name: 'Type 812',
    type: 'T65', country: 'de',
    w: 215, wPublished: false, protein: 11.5, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'German medium extraction. Between T65 and T80.',
    bagImage: '', logo: null,
  },
  {
    id: 'aurora_type405',
    brand: 'Aurora', name: 'Weizenmehl Type 405',
    type: 'all_purpose', country: 'de',
    w: 160, wPublished: false, protein: 10.0, hydration: [56, 62],
    bestFor: [], crowdFavourite: [],
    note: 'German supermarket standard flour. Type 405 (fine white).',
    bagImage: '', logo: null,
  },
  {
    id: 'aurora_type550',
    brand: 'Aurora', name: 'Weizenmehl Type 550',
    type: 'T55', country: 'de',
    w: 195, wPublished: false, protein: 11.0, hydration: [58, 64],
    bestFor: [], crowdFavourite: [],
    note: 'German supermarket Type 550. Standard baking flour.',
    bagImage: '', logo: null,
  },
  {
    id: 'diamant_type405',
    brand: 'Diamant', name: 'Weizenmehl Type 405',
    type: 'all_purpose', country: 'de',
    w: 155, wPublished: false, protein: 9.5, hydration: [55, 61],
    bestFor: [], crowdFavourite: [],
    note: 'German retail 405. Very fine, low protein.',
    bagImage: '', logo: null,
  },
  {
    id: 'edeka_type550',
    brand: 'Edeka', name: 'Weizenmehl Type 550',
    type: 'T55', country: 'de',
    w: 190, wPublished: false, protein: 10.5, hydration: [58, 64],
    bestFor: [], crowdFavourite: [],
    note: 'German supermarket own brand Type 550.',
    bagImage: '', logo: null,
  },
  {
    id: 'rewe_bio_type1050',
    brand: 'Rewe Bio', name: 'Weizenmehl Type 1050',
    type: 'T80', country: 'de',
    w: 195, wPublished: false, protein: 12.0, hydration: [65, 71],
    bestFor: [], crowdFavourite: [],
    note: 'German organic high-extraction. Type 1050. For rustic loaves.',
    bagImage: '', logo: null,
  },
  {
    id: 'bioland_vollkorn',
    brand: 'Bioland', name: 'Vollkornmehl (Wholemeal)',
    type: 'wholemeal', country: 'de',
    w: 210, wPublished: false, protein: 13.0, hydration: [66, 72],
    bestFor: [], crowdFavourite: [],
    note: 'German organic certified wholemeal. Rich in fibre.',
    bagImage: '', logo: null,
  },
  {
    id: 'schapfenmuehle_type550',
    brand: 'Schapfenmühle', name: 'Weizenmehl Type 550',
    type: 'T55', country: 'de',
    w: 220, wPublished: false, protein: 11.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Premium German mill. Good protein for bread baking.',
    bagImage: '', logo: null,
  },
  {
    id: 'mueller_type1050',
    brand: 'Müller\'s Mühle', name: 'Weizenmehl Type 1050',
    type: 'T80', country: 'de',
    w: 200, wPublished: false, protein: 12.5, hydration: [65, 71],
    bestFor: [], crowdFavourite: [],
    note: 'High-extraction German wheat flour. For rustic breads.',
    bagImage: '', logo: null,
  },
  {
    id: 'dinkelvollkorn_de',
    brand: 'Demeter', name: 'Dinkelvollkorn (Spelt Wholemeal)',
    type: 'spelt', country: 'de',
    w: 190, wPublished: false, protein: 12.0, hydration: [63, 69],
    bestFor: [], crowdFavourite: [],
    note: 'Biodynamic certified German spelt wholemeal.',
    bagImage: '', logo: null,
  },
  {
    id: 'roggenvollkorn_de',
    brand: 'Aurora', name: 'Roggenvollkornmehl (Rye Wholemeal)',
    type: 'rye', country: 'de',
    w: 140, wPublished: false, protein: 9.0, hydration: [72, 78],
    bestFor: [], crowdFavourite: [],
    note: 'German rye wholemeal. For Roggenbrot and sourdough.',
    bagImage: '', logo: null,
  },

  // ── Austria ──────────────────────────────────
  {
    id: 'griessler_w700',
    brand: 'Wiener Griessler', name: 'Weizenmehl W700',
    type: 'T55', country: 'at',
    w: 220, wPublished: false, protein: 11.0, hydration: [59, 65],
    bestFor: [], crowdFavourite: [],
    note: 'Austrian W700 (standard bread flour). Similar to German 550.',
    bagImage: '', logo: null,
  },
  {
    id: 'muehle_ebner_w1600',
    brand: 'Mühle Ebner', name: 'Weizenmehl W1600',
    type: 'T80', country: 'at',
    w: 200, wPublished: false, protein: 12.5, hydration: [64, 70],
    bestFor: [], crowdFavourite: [],
    note: 'Austrian high-extraction flour. For dark rustic breads.',
    bagImage: '', logo: null,
  },
  {
    id: 'waldviertler_dinkel',
    brand: 'Waldviertler', name: 'Dinkelvollkorn',
    type: 'spelt', country: 'at',
    w: 185, wPublished: false, protein: 12.0, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'Austrian organic spelt. Regional heritage grain.',
    bagImage: '', logo: null,
  },

  // ── Netherlands ──────────────────────────────
  {
    id: 'meneba_bread',
    brand: 'Meneba', name: 'Bread Flour',
    type: 'bread', country: 'nl',
    w: 245, wPublished: false, protein: 12.5, hydration: [61, 67],
    bestFor: [], crowdFavourite: [],
    note: 'Major Dutch mill. Professional bread flour. Used by Dutch bakeries.',
    bagImage: '', logo: null,
  },
  {
    id: 'patent_bloem_nl',
    brand: 'Koopmans', name: 'Patentbloem',
    type: 'all_purpose', country: 'nl',
    w: 175, wPublished: false, protein: 10.5, hydration: [57, 63],
    bestFor: [], crowdFavourite: [],
    note: 'Standard Dutch all-purpose flour. Most common retail flour in Netherlands.',
    bagImage: '', logo: null,
  },
  {
    id: 'koopmans_brood',
    brand: 'Koopmans', name: 'Broodmix Tarwebloem',
    type: 'bread', country: 'nl',
    w: 230, wPublished: false, protein: 12.0, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Dutch retail bread flour.',
    bagImage: '', logo: null,
  },

  // ── Scandinavia ──────────────────────────────
  {
    id: 'fazer_bread_fi',
    brand: 'Fazer', name: 'Vehnäjauho (Wheat Flour)',
    type: 'bread', country: 'fi',
    w: 230, wPublished: false, protein: 12.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Leading Finnish flour brand. For Finnish bread baking.',
    bagImage: '', logo: null,
  },
  {
    id: 'mills_hvetemel_no',
    brand: 'Mills', name: 'Hvetemel (Wheat Flour)',
    type: 'bread', country: 'no',
    w: 235, wPublished: false, protein: 12.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Leading Norwegian flour brand. For bread and baking.',
    bagImage: '', logo: null,
  },
  {
    id: 'kung_markatta_spelt_se',
    brand: 'Kung Markatta', name: 'Dinkelvetemjöl (Spelt)',
    type: 'spelt', country: 'se',
    w: 190, wPublished: false, protein: 11.5, hydration: [61, 67],
    bestFor: [], crowdFavourite: [],
    note: 'Swedish organic spelt flour. Popular in Scandinavian artisan baking.',
    bagImage: '', logo: null,
  },
  {
    id: 'coop_vetemjol_se',
    brand: 'Coop', name: 'Vetemjöl (All Purpose)',
    type: 'all_purpose', country: 'se',
    w: 175, wPublished: false, protein: 10.5, hydration: [57, 63],
    bestFor: [], crowdFavourite: [],
    note: 'Swedish supermarket own brand all-purpose flour.',
    bagImage: '', logo: null,
  },

  // ── More US ──────────────────────────────────
  {
    id: 'ardent_mills_occident',
    brand: 'Ardent Mills', name: 'Occident Flour',
    type: 'all_purpose', country: 'us',
    w: 195, wPublished: false, protein: 11.5, hydration: [59, 65],
    bestFor: [], crowdFavourite: [],
    note: 'Premium US AP from major commercial mill. Higher protein than Gold Medal.',
    bagImage: '', logo: null,
  },
  {
    id: 'ardent_mills_hi_gluten',
    brand: 'Ardent Mills', name: 'High Gluten Flour',
    type: 'high_gluten', country: 'us',
    w: 310, wPublished: false, protein: 14.2, hydration: [64, 70],
    bestFor: [], crowdFavourite: [],
    note: 'Professional high-gluten for NY pizza and bagels.',
    bagImage: '', logo: null,
  },
  {
    id: 'wheat_montana_natural',
    brand: 'Wheat Montana', name: 'Natural White Flour',
    type: 'all_purpose', country: 'us',
    w: 200, wPublished: false, protein: 11.5, hydration: [59, 65],
    bestFor: [], crowdFavourite: [],
    note: 'Montana hard white wheat. Single-source farm. Clean flavour.',
    bagImage: '', logo: null,
  },
  {
    id: 'wheat_montana_bread',
    brand: 'Wheat Montana', name: 'Bronze Chief Bread Flour',
    type: 'bread', country: 'us',
    w: 265, wPublished: false, protein: 14.0, hydration: [63, 69],
    bestFor: [], crowdFavourite: [],
    note: 'Hard red spring wheat. Very high protein. For sourdough.',
    bagImage: '', logo: null,
  },
  {
    id: 'ceresota_ap',
    brand: 'Ceresota / Heckers', name: 'Unbleached All Purpose',
    type: 'all_purpose', country: 'us',
    w: 190, wPublished: false, protein: 11.5, hydration: [59, 65],
    bestFor: [], crowdFavourite: [],
    note: 'Midwest US regional AP flour. Higher protein than national brands.',
    bagImage: '', logo: null,
  },
  {
    id: 'lehi_bread',
    brand: 'Lehi Roller Mills', name: 'Bread Flour',
    type: 'bread', country: 'us',
    w: 255, wPublished: false, protein: 13.0, hydration: [61, 67],
    bestFor: [], crowdFavourite: [],
    note: 'Utah regional mill. Good protein content for artisan bread.',
    bagImage: '', logo: null,
  },
  {
    id: 'arrowhead_ap',
    brand: 'Arrowhead Mills', name: 'Organic All Purpose',
    type: 'all_purpose', country: 'us',
    w: 185, wPublished: false, protein: 11.0, hydration: [58, 64],
    bestFor: [], crowdFavourite: [],
    note: 'Organic US AP. Available in health food stores.',
    bagImage: '', logo: null,
  },
  {
    id: 'great_river_bread',
    brand: 'Great River Organic', name: 'Bread Flour',
    type: 'bread', country: 'us',
    w: 255, wPublished: false, protein: 13.5, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'Midwest organic mill. Stone ground option. For artisan sourdough.',
    bagImage: '', logo: null,
  },
  {
    id: 'sunrise_bread',
    brand: 'Sunrise Flour Mill', name: 'Heritage Bread Flour',
    type: 'bread', country: 'us',
    w: 245, wPublished: false, protein: 12.5, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'Heritage variety wheat. Lower W but complex flavour.',
    bagImage: '', logo: null,
  },
  {
    id: 'pendleton_power',
    brand: 'Pendleton Flour Mills', name: 'Power Flour',
    type: 'high_gluten', country: 'us',
    w: 310, wPublished: false, protein: 14.5, hydration: [64, 70],
    bestFor: [], crowdFavourite: [],
    note: 'Pacific NW high-gluten. For bagels and NY-style pizza.',
    bagImage: '', logo: null,
  },
  {
    id: 'bay_state_special_patent',
    brand: 'Bay State Milling', name: 'Special Patent',
    type: 'all_purpose', country: 'us',
    w: 220, wPublished: false, protein: 12.0, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'US professional patent flour. For pizza, rolls, and light bread.',
    bagImage: '', logo: null,
  },
  {
    id: 'whole_foods_365_bread',
    brand: 'Whole Foods 365', name: 'Organic Bread Flour',
    type: 'bread', country: 'us',
    w: 240, wPublished: false, protein: 12.5, hydration: [61, 67],
    bestFor: [], crowdFavourite: [],
    note: 'Organic store brand. Common across US.',
    bagImage: '', logo: null,
  },
  {
    id: 'bobs_whole_wheat',
    brand: "Bob's Red Mill", name: 'Organic Whole Wheat Flour',
    type: 'wholemeal', country: 'us',
    w: 215, wPublished: false, protein: 13.5, hydration: [65, 71],
    bestFor: [], crowdFavourite: [],
    note: 'Organic whole wheat. Popular US health food brand.',
    bagImage: '', logo: null,
  },
  {
    id: 'ka_white_whole_wheat',
    brand: 'King Arthur', name: 'White Whole Wheat Flour',
    type: 'wholemeal', country: 'us',
    w: 220, wPublished: false, protein: 13.0, hydration: [64, 70],
    bestFor: [], crowdFavourite: [],
    note: 'Hard white wheat. Milder than red whole wheat. Great for whole grain loaves.',
    bagImage: '', logo: null,
  },
  {
    id: 'hayden_mills_ap',
    brand: 'Hayden Flour Mills', name: 'All Purpose',
    type: 'all_purpose', country: 'us',
    w: 190, wPublished: false, protein: 11.5, hydration: [58, 64],
    bestFor: [], crowdFavourite: [],
    note: 'Heritage grain Arizona mill. Single-origin. For artisan bread.',
    bagImage: '', logo: null,
  },
  {
    id: 'king_midas_bread',
    brand: 'King Midas', name: 'Better for Bread',
    type: 'bread', country: 'us',
    w: 235, wPublished: false, protein: 12.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'US bread flour. Regional availability in Central and South US.',
    bagImage: '', logo: null,
  },

  // ── Canada ───────────────────────────────────
  {
    id: 'rogers_bread',
    brand: 'Rogers', name: 'Bread Flour',
    type: 'bread', country: 'ca',
    w: 265, wPublished: false, protein: 13.5, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'Western Canada flour. High protein prairie wheat.',
    bagImage: '', logo: null,
  },
  {
    id: 'prairie_tradition_ap',
    brand: 'Prairie Tradition', name: 'All Purpose Flour',
    type: 'all_purpose', country: 'ca',
    w: 225, wPublished: false, protein: 13.0, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Canadian organic AP flour. Hard red spring wheat.',
    bagImage: '', logo: null,
  },
  {
    id: 'nunweilers_wholegrain',
    brand: "Nunweiler's", name: 'Whole Grain Flour',
    type: 'wholemeal', country: 'ca',
    w: 225, wPublished: false, protein: 14.0, hydration: [65, 71],
    bestFor: [], crowdFavourite: [],
    note: 'Saskatchewan organic whole grain. Stone ground. For sourdough.',
    bagImage: '', logo: null,
  },

  // ── More Australian ──────────────────────────
  {
    id: 'laucke_wallaby',
    brand: 'Laucke', name: 'Wallaby Bakers Flour',
    type: 'bread', country: 'au',
    w: 255, wPublished: false, protein: 12.5, hydration: [61, 67],
    bestFor: [], crowdFavourite: [],
    note: 'Australian premium bakers flour. Widely used by home and professional bakers.',
    bagImage: '', logo: null,
  },
  {
    id: 'laucke_crusty_white',
    brand: 'Laucke', name: 'Crusty White Bread Mix',
    type: 'bread', country: 'au',
    w: 245, wPublished: false, protein: 12.0, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Australian retail bread flour. Good for home sourdough.',
    bagImage: '', logo: null,
  },
  {
    id: 'manildra_bakers',
    brand: 'Manildra', name: 'Bakers Flour',
    type: 'bread', country: 'au',
    w: 250, wPublished: false, protein: 12.5, hydration: [61, 67],
    bestFor: [], crowdFavourite: [],
    note: 'Australian commercial bakers flour. Widely distributed.',
    bagImage: '', logo: null,
  },
  {
    id: 'lighthouse_bread',
    brand: 'Lighthouse', name: 'Bread & Pizza Flour',
    type: 'bread', country: 'au',
    w: 240, wPublished: false, protein: 12.0, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Australian supermarket bread flour. Fortified. Common across AU.',
    bagImage: '', logo: null,
  },

  // ── More Japan ───────────────────────────────
  {
    id: 'nippn_lysdor',
    brand: "Nippn", name: "Lys d'Or",
    type: '00', country: 'jp',
    w: 310, wPublished: false, protein: 14.5, hydration: [63, 69],
    bestFor: [], crowdFavourite: [],
    note: 'High-gluten Japanese flour. Very popular in Japan for pizza and bread.',
    bagImage: '', logo: null,
  },
  {
    id: 'nippn_super_king',
    brand: 'Nippn', name: 'Super King',
    type: 'bread', country: 'jp',
    w: 300, wPublished: false, protein: 13.8, hydration: [63, 69],
    bestFor: [], crowdFavourite: [],
    note: 'Premium Japanese high-protein bread flour. For Japanese milk bread.',
    bagImage: '', logo: null,
  },
  {
    id: 'haruyutaka_spring_wheat',
    brand: 'Sapporo Seifun', name: 'Haruyutaka',
    type: 'bread', country: 'jp',
    w: 270, wPublished: false, protein: 13.5, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: '100% Hokkaido spring wheat. Prized by Japanese artisan bakers.',
    bagImage: '', logo: null,
  },
  {
    id: 'kitanokaori_hokkaido',
    brand: 'Sapporo Seifun', name: 'Kitanokaori',
    type: 'bread', country: 'jp',
    w: 280, wPublished: false, protein: 14.0, hydration: [63, 69],
    bestFor: [], crowdFavourite: [],
    note: 'Hokkaido hard wheat variety. Aromatic. For premium Japanese bread.',
    bagImage: '', logo: null,
  },
  {
    id: 'showa_dolce',
    brand: 'Showa', name: 'Dolce Soft Flour',
    type: 'all_purpose', country: 'jp',
    w: 160, wPublished: false, protein: 8.0, hydration: [54, 60],
    bestFor: [], crowdFavourite: [],
    note: 'Japanese soft flour for cakes and pastries. Very low protein.',
    bagImage: '', logo: null,
  },
  {
    id: 'nisshin_violet_bread',
    brand: 'Nisshin', name: 'Super Hard Flour',
    type: 'bread', country: 'jp',
    w: 310, wPublished: false, protein: 14.5, hydration: [64, 70],
    bestFor: [], crowdFavourite: [],
    note: 'Professional high-gluten Japanese flour. For hard rolls and pizza.',
    bagImage: '', logo: null,
  },
  {
    id: 'meiji_bread',
    brand: 'Meiji', name: 'Premium Bread Flour',
    type: 'bread', country: 'jp',
    w: 270, wPublished: false, protein: 13.5, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'Japanese retail bread flour. For shokupan and soft rolls.',
    bagImage: '', logo: null,
  },
  {
    id: 'tokiwa_semolina_jp',
    brand: 'Tokiwa', name: 'Semolina Durum',
    type: 'semolina', country: 'jp',
    w: 195, wPublished: false, protein: 13.0, hydration: [59, 65],
    bestFor: [], crowdFavourite: [],
    note: 'Japanese semolina for pizza bases and pasta.',
    bagImage: '', logo: null,
  },

  // ── Korea ────────────────────────────────────
  {
    id: 'beksul_ap',
    brand: 'Beksul (CJ)', name: 'All Purpose Flour',
    type: 'all_purpose', country: 'kr',
    w: 170, wPublished: false, protein: 10.5, hydration: [57, 63],
    bestFor: [], crowdFavourite: [],
    note: 'Most popular Korean household flour. Available everywhere in Korea.',
    bagImage: '', logo: null,
  },
  {
    id: 'beksul_strong',
    brand: 'Beksul (CJ)', name: 'Strong Flour (강력분)',
    type: 'bread', country: 'kr',
    w: 245, wPublished: false, protein: 13.0, hydration: [61, 67],
    bestFor: [], crowdFavourite: [],
    note: 'Korean bread flour (강력분). For Korean-style bread and pizza.',
    bagImage: '', logo: null,
  },
  {
    id: 'ottogi_strong',
    brand: 'Ottogi', name: 'Strong Bread Flour',
    type: 'bread', country: 'kr',
    w: 240, wPublished: false, protein: 13.0, hydration: [61, 67],
    bestFor: [], crowdFavourite: [],
    note: 'Korean 강력분 from Ottogi. Available in Korean supermarkets.',
    bagImage: '', logo: null,
  },
  {
    id: 'sajo_strong',
    brand: 'Sajo Haepyo', name: 'Premium Strong Flour',
    type: 'bread', country: 'kr',
    w: 255, wPublished: false, protein: 13.5, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'Premium Korean bread flour. High protein Canadian wheat blend.',
    bagImage: '', logo: null,
  },
  {
    id: 'daehan_ap',
    brand: 'Daehan Flour Mills', name: 'All Purpose',
    type: 'all_purpose', country: 'kr',
    w: 175, wPublished: false, protein: 10.5, hydration: [57, 63],
    bestFor: [], crowdFavourite: [],
    note: 'Korean flour mill. Widely used in Korean bakeries and homes.',
    bagImage: '', logo: null,
  },
  {
    id: 'pungnyon_bread',
    brand: 'Pungnyon', name: 'Bread Flour (강력분)',
    type: 'bread', country: 'kr',
    w: 245, wPublished: false, protein: 13.0, hydration: [61, 67],
    bestFor: [], crowdFavourite: [],
    note: 'Korean bread flour from Pungnyon Mill.',
    bagImage: '', logo: null,
  },

  // ── Indonesia ────────────────────────────────
  {
    id: 'bogasari_cakra',
    brand: 'Bogasari', name: 'Cakra Kembar (Bread Flour)',
    type: 'bread', country: 'id',
    w: 250, wPublished: false, protein: 13.0, hydration: [61, 67],
    bestFor: [], crowdFavourite: [],
    note: 'Indonesia\'s premium bread flour. Blue pack. Widely used in Indonesian bakeries.',
    bagImage: '', logo: null,
  },
  {
    id: 'bogasari_segitiga',
    brand: 'Bogasari', name: 'Segitiga Biru (All Purpose)',
    type: 'all_purpose', country: 'id',
    w: 175, wPublished: false, protein: 10.5, hydration: [57, 63],
    bestFor: [], crowdFavourite: [],
    note: 'Most common Indonesian household flour. Blue triangle logo.',
    bagImage: '', logo: null,
  },
  {
    id: 'bogasari_kompas',
    brand: 'Bogasari', name: 'Kompas (Medium Flour)',
    type: 'all_purpose', country: 'id',
    w: 190, wPublished: false, protein: 11.0, hydration: [58, 64],
    bestFor: [], crowdFavourite: [],
    note: 'Indonesian medium protein flour. Between AP and bread flour.',
    bagImage: '', logo: null,
  },
  {
    id: 'sriboga_bread',
    brand: 'Sriboga', name: 'Bread Flour',
    type: 'bread', country: 'id',
    w: 245, wPublished: false, protein: 12.5, hydration: [61, 67],
    bestFor: [], crowdFavourite: [],
    note: 'Indonesian bread flour. Available in Indonesian supermarkets.',
    bagImage: '', logo: null,
  },

  // ── Philippines ──────────────────────────────
  {
    id: 'maya_bread_ph',
    brand: 'Maya', name: 'Bread Flour',
    type: 'bread', country: 'ph',
    w: 240, wPublished: false, protein: 12.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Leading Philippine flour brand. For pandesal and Filipino bread.',
    bagImage: '', logo: null,
  },
  {
    id: 'maya_ap_ph',
    brand: 'Maya', name: 'All Purpose Flour',
    type: 'all_purpose', country: 'ph',
    w: 165, wPublished: false, protein: 9.5, hydration: [56, 62],
    bestFor: [], crowdFavourite: [],
    note: 'Philippine all-purpose household flour.',
    bagImage: '', logo: null,
  },
  {
    id: 'pilmico_bread_ph',
    brand: 'Pilmico', name: 'Bread Flour',
    type: 'bread', country: 'ph',
    w: 240, wPublished: false, protein: 12.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Philippine commercial bread flour. Widely used in Philippine bakeries.',
    bagImage: '', logo: null,
  },

  // ── Thailand ─────────────────────────────────
  {
    id: 'royal_bread_th',
    brand: 'Royal', name: 'Bread Flour',
    type: 'bread', country: 'th',
    w: 240, wPublished: false, protein: 13.0, hydration: [61, 67],
    bestFor: [], crowdFavourite: [],
    note: 'Thai bread flour. Popular in Thai and Southeast Asian bakeries.',
    bagImage: '', logo: null,
  },
  {
    id: 'president_bread_th',
    brand: 'President', name: 'Bread Flour',
    type: 'bread', country: 'th',
    w: 245, wPublished: false, protein: 13.0, hydration: [61, 67],
    bestFor: [], crowdFavourite: [],
    note: 'Thai commercial bread flour. High protein. Used in Thai bakeries.',
    bagImage: '', logo: null,
  },
  {
    id: 'benjakul_bread_th',
    brand: 'Benjakul', name: 'Bread Flour',
    type: 'bread', country: 'th',
    w: 235, wPublished: false, protein: 12.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Thai flour brand. For Thai bakery applications.',
    bagImage: '', logo: null,
  },

  // ── Specialty / Heritage ─────────────────────
  {
    id: 'generic_spelt',
    brand: 'Generic', name: 'Spelt Flour / Épeautre',
    type: 'spelt', country: 'de',
    w: 195, wPublished: false, protein: 12.0, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'Generic spelt estimate. Extensible but weak gluten. Use ≤30% in blends.',
    bagImage: '', logo: null,
  },
  {
    id: 'generic_einkorn',
    brand: 'Generic', name: 'Einkorn Flour',
    type: 'wholemeal', country: 'it',
    w: 160, wPublished: false, protein: 14.0, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Ancient wheat. High protein but very weak gluten structure. Specialty use.',
    bagImage: '', logo: null,
  },
  {
    id: 'generic_emmer',
    brand: 'Generic', name: 'Emmer / Farro Medio',
    type: 'wholemeal', country: 'it',
    w: 170, wPublished: false, protein: 13.5, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'Ancient grain. Nutty flavour. Use 10-30% in blend for depth of flavour.',
    bagImage: '', logo: null,
  },
  {
    id: 'generic_khorasan',
    brand: 'Generic', name: 'Khorasan / Kamut',
    type: 'wholemeal', country: 'us',
    w: 180, wPublished: false, protein: 14.5, hydration: [63, 69],
    bestFor: [], crowdFavourite: [],
    note: 'Ancient wheat variety. High protein, extensible. Earthy buttery flavour.',
    bagImage: '', logo: null,
  },
  {
    id: 'jovial_einkorn_us',
    brand: 'Jovial Foods', name: 'Organic Einkorn AP',
    type: 'all_purpose', country: 'us',
    w: 155, wPublished: false, protein: 14.0, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'US packaged einkorn flour. Popular in ancient grain baking community.',
    bagImage: '', logo: null,
  },
  {
    id: 'kamut_brand',
    brand: 'KAMUT', name: 'Khorasan Wheat Flour',
    type: 'wholemeal', country: 'us',
    w: 175, wPublished: false, protein: 14.5, hydration: [63, 69],
    bestFor: [], crowdFavourite: [],
    note: 'Trademarked Khorasan variety. Certified organic. Buttery flavour.',
    bagImage: '', logo: null,
  },
  {
    id: 'doves_farm_rye',
    brand: 'Doves Farm', name: 'Organic Rye Flour',
    type: 'rye', country: 'uk',
    w: 145, wPublished: false, protein: 8.0, hydration: [70, 76],
    bestFor: [], crowdFavourite: [],
    note: 'UK organic rye. For sourdough starters, rye crackers, and rye breads.',
    bagImage: '', logo: null,
  },
  {
    id: 'shipton_spelt',
    brand: 'Shipton Mill', name: 'Organic Spelt White',
    type: 'spelt', country: 'uk',
    w: 200, wPublished: false, protein: 12.0, hydration: [61, 67],
    bestFor: [], crowdFavourite: [],
    note: 'White spelt flour. Lighter than wholemeal spelt. For artisan bakers.',
    bagImage: '', logo: null,
  },
  {
    id: 'central_whole_wheat',
    brand: 'Central Milling', name: 'Organic Whole Wheat',
    type: 'wholemeal', country: 'us',
    w: 225, wPublished: false, protein: 14.0, hydration: [66, 72],
    bestFor: [], crowdFavourite: [],
    note: 'Premium US organic whole wheat. For sourdough and whole grain loaves.',
    bagImage: '', logo: null,
  },
  {
    id: 'ka_rye',
    brand: 'King Arthur', name: 'Dark Rye Flour',
    type: 'rye', country: 'us',
    w: 150, wPublished: false, protein: 9.0, hydration: [72, 78],
    bestFor: [], crowdFavourite: [],
    note: 'US dark rye. For sourdough starters, rye breads, and cocktail rye.',
    bagImage: '', logo: null,
  },

  // ── Vietnam ──────────────────────────────────
  {
    id: 'binh_tay_bread_vn',
    brand: 'Bột Mì Bình Tây', name: 'Bread Flour',
    type: 'bread', country: 'vn',
    w: 235, wPublished: false, protein: 12.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Vietnamese bread flour. Popular in Vietnamese bakeries for bánh mì.',
    bagImage: '', logo: null,
  },
  {
    id: 'viet_bakery_strong',
    brand: 'Viet Bakery', name: 'Strong Flour',
    type: 'bread', country: 'vn',
    w: 245, wPublished: false, protein: 13.0, hydration: [61, 67],
    bestFor: [], crowdFavourite: [],
    note: 'Vietnamese commercial bread flour for professional bakeries.',
    bagImage: '', logo: null,
  },

  // ── China ────────────────────────────────────
  {
    id: 'guji_bread_cn',
    brand: '古吉 (Guji)', name: '高筋面粉 (High Gluten)',
    type: 'bread', country: 'cn',
    w: 240, wPublished: false, protein: 13.0, hydration: [61, 67],
    bestFor: [], crowdFavourite: [],
    note: 'Chinese high-gluten flour (高筋). For Chinese bread, pizza, and noodles.',
    bagImage: '', logo: null,
  },
  {
    id: 'wudeli_ap_cn',
    brand: '五得利 (Wudeli)', name: '通用面粉 (All Purpose)',
    type: 'all_purpose', country: 'cn',
    w: 175, wPublished: false, protein: 11.0, hydration: [57, 63],
    bestFor: [], crowdFavourite: [],
    note: 'China\'s largest flour brand. Standard household flour. Available nationwide.',
    bagImage: '', logo: null,
  },
  {
    id: 'jinlong_bread_cn',
    brand: '金龙鱼 (Jinlongyu)', name: '高筋面粉',
    type: 'bread', country: 'cn',
    w: 245, wPublished: false, protein: 13.0, hydration: [61, 67],
    bestFor: [], crowdFavourite: [],
    note: 'Major Chinese supermarket brand. High-gluten flour for bread and pizza.',
    bagImage: '', logo: null,
  },

  // ── India ────────────────────────────────────
  {
    id: 'pillsbury_india_atta',
    brand: 'Pillsbury India', name: 'Chakki Fresh Atta',
    type: 'wholemeal', country: 'in',
    w: 180, wPublished: false, protein: 12.0, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Indian whole wheat atta. Stone ground. For chapati and flatbread. Can be used in sourdough.',
    bagImage: '', logo: null,
  },
  {
    id: 'aashirvaad_atta',
    brand: 'Aashirvaad', name: 'Select Whole Wheat Atta',
    type: 'wholemeal', country: 'in',
    w: 185, wPublished: false, protein: 12.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Leading Indian whole wheat brand. Good protein from hard wheat blend.',
    bagImage: '', logo: null,
  },
  {
    id: 'annapurna_maida_in',
    brand: 'Annapurna', name: 'Maida (Refined Flour)',
    type: 'all_purpose', country: 'in',
    w: 160, wPublished: false, protein: 9.5, hydration: [55, 61],
    bestFor: [], crowdFavourite: [],
    note: 'Indian refined white flour (maida). For naan, paratha, and pastries.',
    bagImage: '', logo: null,
  },

  // ── Malaysia extended ─────────────────────────
  {
    id: 'cap_sauh_bread_my',
    brand: 'Cap Sauh', name: 'High Protein Flour',
    type: 'bread', country: 'my',
    w: 245, wPublished: false, protein: 13.0, hydration: [61, 67],
    bestFor: [], crowdFavourite: [],
    note: 'Malaysian bread flour. Anchor logo. Available in Malaysian supermarkets.',
    bagImage: '', logo: null,
  },
  {
    id: 'golden_pineapple_ap',
    brand: 'Golden Pineapple', name: 'All Purpose Flour',
    type: 'all_purpose', country: 'my',
    w: 165, wPublished: false, protein: 10.0, hydration: [56, 62],
    bestFor: [], crowdFavourite: [],
    note: 'Malaysian household flour. Standard AP for everyday baking.',
    bagImage: '', logo: null,
  },

  // ── Poland ───────────────────────────────────
  {
    id: 'lubella_type500',
    brand: 'Lubella', name: 'Mąka Pszenna Typ 500',
    type: 'T55', country: 'pl',
    w: 185, wPublished: false, protein: 11.0, hydration: [58, 64],
    bestFor: [], crowdFavourite: [],
    note: 'Poland\'s most popular flour brand. Typ 500 is standard white.',
    bagImage: '', logo: null,
  },
  {
    id: 'szymanowski_type550',
    brand: 'Szymanowski', name: 'Mąka Pszenna Chlebowa',
    type: 'bread', country: 'pl',
    w: 230, wPublished: false, protein: 12.5, hydration: [61, 67],
    bestFor: [], crowdFavourite: [],
    note: 'Polish bread flour. For traditional Polish bread and rolls.',
    bagImage: '', logo: null,
  },
  {
    id: 'polskie_mlynarstwo_rye',
    brand: 'Polskie Młynarstwo', name: 'Mąka Żytnia Typ 720',
    type: 'rye', country: 'pl',
    w: 145, wPublished: false, protein: 8.5, hydration: [71, 77],
    bestFor: [], crowdFavourite: [],
    note: 'Polish light rye flour. For traditional chleb razowy and sourdough.',
    bagImage: '', logo: null,
  },

  // ── Brazil ───────────────────────────────────
  {
    id: 'renata_bread_br',
    brand: 'Renata', name: 'Farinha de Trigo Especial',
    type: 'all_purpose', country: 'br',
    w: 195, wPublished: false, protein: 11.5, hydration: [59, 65],
    bestFor: [], crowdFavourite: [],
    note: 'Brazil\'s most popular flour brand. Higher protein than US AP.',
    bagImage: '', logo: null,
  },
  {
    id: 'anaconda_bread_br',
    brand: 'Anaconda', name: 'Farinha para Pão',
    type: 'bread', country: 'br',
    w: 235, wPublished: false, protein: 12.5, hydration: [60, 66],
    bestFor: [], crowdFavourite: [],
    note: 'Brazilian bread flour. For pão de forma and artisan bread.',
    bagImage: '', logo: null,
  },

  // ── More Italian specialty ────────────────────
  {
    id: 'molino_spadoni_00',
    brand: 'Molino Spadoni', name: 'Farina 00 Pizza',
    type: '00', country: 'it',
    w: 230, wPublished: false, protein: 11.5, hydration: [58, 64],
    bestFor: [], crowdFavourite: [],
    note: 'Italian supermarket 00. Widely available in Italian mass retail.',
    bagImage: '', logo: null,
  },
  {
    id: 'caputo_rinforzato',
    brand: 'Caputo', name: 'Rinforzato',
    type: 'high_gluten', country: 'it',
    w: 280, wPublished: true, protein: 13.0, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'Reinforced 00. For biga and poolish preferment techniques.',
    bagImage: '', logo: null,
  },
  {
    id: 'petra_9_bio',
    brand: 'Petra', name: '9 Bio',
    type: 'wholemeal', country: 'it',
    w: 245, wPublished: false, protein: 13.0, hydration: [65, 71],
    bestFor: [], crowdFavourite: [],
    note: 'Organic whole wheat Petra. Stone ground. For sourdough whole grain pizza.',
    bagImage: '', logo: null,
  },
  {
    id: 'mulino_marino_farro',
    brand: 'Mulino Marino', name: 'Farro Semintegrale',
    type: 'spelt', country: 'it',
    w: 185, wPublished: false, protein: 13.0, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'Italian semi-wholemeal spelt (farro). Stone ground. Complex flavour.',
    bagImage: '', logo: null,
  },

  // ── More French specialty ─────────────────────
  {
    id: 'gmp_t150',
    brand: 'Grands Moulins de Paris', name: 'T150 Intégrale',
    type: 'T150', country: 'fr',
    w: 180, wPublished: false, protein: 13.0, hydration: [68, 74],
    bestFor: [], crowdFavourite: [],
    note: 'Full wholemeal French flour. Maximum bran content.',
    bagImage: '', logo: null,
  },
  {
    id: 'francine_complete',
    brand: 'Francine', name: 'Farine Complète T150',
    type: 'T150', country: 'fr',
    w: 175, wPublished: false, protein: 13.0, hydration: [68, 74],
    bestFor: [], crowdFavourite: [],
    note: 'French supermarket wholemeal. For pain complet.',
    bagImage: '', logo: null,
  },

  // ── More US specialty ─────────────────────────
  {
    id: 'bobs_dark_rye',
    brand: "Bob's Red Mill", name: 'Dark Rye Flour',
    type: 'rye', country: 'us',
    w: 145, wPublished: false, protein: 9.0, hydration: [72, 78],
    bestFor: [], crowdFavourite: [],
    note: 'US dark rye. For sourdough, rye breads, and pumpernickel.',
    bagImage: '', logo: null,
  },
  {
    id: 'gold_medal_whole_wheat',
    brand: 'Gold Medal', name: 'Whole Wheat Flour',
    type: 'wholemeal', country: 'us',
    w: 205, wPublished: false, protein: 13.5, hydration: [65, 71],
    bestFor: [], crowdFavourite: [],
    note: 'US mainstream whole wheat. Available in all US supermarkets.',
    bagImage: '', logo: null,
  },
  {
    id: 'white_sonora_heritage',
    brand: 'Hayden Flour Mills', name: 'White Sonora Wheat',
    type: 'all_purpose', country: 'us',
    w: 155, wPublished: false, protein: 10.0, hydration: [58, 64],
    bestFor: [], crowdFavourite: [],
    note: 'Heritage heirloom wheat. Low W but beautiful flavour. For flatbreads.',
    bagImage: '', logo: null,
  },
  {
    id: 'primavera_ap_sg',
    brand: 'Primavera', name: 'All Purpose Flour',
    type: 'all_purpose', country: 'sg',
    w: 165, wPublished: false, protein: 9.5, hydration: [56, 62],
    bestFor: [], crowdFavourite: [],
    note: 'Singapore all-purpose household flour. Available in FairPrice.',
    bagImage: '', logo: null,
  },
  {
    id: 'golden_pagoda_bread_sg',
    brand: 'Golden Pagoda', name: 'Bread Flour',
    type: 'bread', country: 'sg',
    w: 245, wPublished: false, protein: 12.5, hydration: [61, 67],
    bestFor: [], crowdFavourite: [],
    note: 'Singapore commercial bread flour brand.',
    bagImage: '', logo: null,
  },
  {
    id: 'anitas_bread_ca',
    brand: "Anita's", name: 'Organic Bread Flour',
    type: 'bread', country: 'ca',
    w: 255, wPublished: false, protein: 13.5, hydration: [62, 68],
    bestFor: [], crowdFavourite: [],
    note: 'Premium Canadian organic bread flour. Hard red spring wheat.',
    bagImage: '', logo: null,
  },
  {
    id: 'petra_5100',
    brand: 'Petra', name: '5100',
    type: '00', country: 'it',
    w: 230, wPublished: false, protein: 12.0, hydration: [58, 64],
    bestFor: [], crowdFavourite: [],
    note: 'Entry-level Petra 00. For quick doughs and shorter ferments.',
    bagImage: '', logo: null,
  },
];
